{
  "env": {
    "browser": true,
    "es2021": true,
    "node": true
  },
  "extends": [
    "eslint:recommended"
  ],
  "parserOptions": {
    "ecmaVersion": "latest",
    "sourceType": "module"
  },
  "rules": {
    "@angular-eslint_contextual-lifecycle": 1,
    "@angular-eslint_no-async-lifecycle-method": 1,
    "@angular-eslint_no-attribute-decorator": 1,
    "@angular-eslint_sort-lifecycle-methods": 1,
    "array-callback-return": 1,
    "ava_assertion-arguments": 1,
    "ava_no-duplicate-modifiers": 1,
    "ava_no-identical-title": 1,
    "ava_no-nested-tests": 1,
    "ava_no-unknown-modifiers": 1,
    "ava_test-title": 1,
    "ava_use-t-throws-async-well": 1,
    "ava_use-t-well": 1,
    "compat_compat": 1,
    "constructor-super": 1,
    "cypress_assertion-before-screenshot": 1,
    "cypress_no-assigning-return-values": 1,
    "cypress_no-async-before": 1,
    "cypress_no-async-tests": 1,
    "cypress_no-unnecessary-waiting": 1,
    "cypress_unsafe-to-chain-command": [
      1,
      [
        {
          "name": "methods",
          "value": "[]"
        }
      ]
    ],
    "ember_avoid-leaking-state-in-ember-objects": 1,
    "ember_classic-decorator-hooks": 1,
    "ember_classic-decorator-no-classic-methods": 1,
    "ember_jquery-ember-run": 1,
    "ember_new-module-imports": 1,
    "ember_no-arrow-function-computed-properties": [
      1,
      [
        {
          "name": "onlyThisContexts",
          "value": "false"
        }
      ]
    ],
    "ember_no-assignment-of-untracked-properties-used-in-tracking-contexts": 1,
    "ember_no-attrs-in-components": 1,
    "ember_no-attrs-snapshot": 1,
    "ember_no-capital-letters-in-routes": 1,
    "ember_no-controller-access-in-routes": [
      1,
      [
        {
          "name": "allowControllerFor",
          "value": "false"
        }
      ]
    ],
    "ember_no-deeply-nested-dependent-keys-with-each": 1,
    "ember_no-duplicate-dependent-keys": 1,
    "ember_no-ember-super-in-es-classes": 1,
    "ember_no-ember-testing-in-module-scope": 1,
    "ember_no-incorrect-calls-with-inline-anonymous-functions": 1,
    "ember_no-incorrect-computed-macros": 1,
    "ember_no-invalid-debug-function-arguments": 1,
    "ember_no-invalid-dependent-keys": 1,
    "ember_no-noop-setup-on-error-in-before": 1,
    "ember_no-restricted-resolver-tests": 1,
    "ember_no-runloop": 1,
    "ember_no-shadow-route-definition": 1,
    "ember_no-side-effects": [
      1,
      [
        {
          "name": "catchEvents",
          "value": "true"
        },
        {
          "name": "checkPlainGetters",
          "value": "true"
        }
      ]
    ],
    "ember_no-test-import-export": 1,
    "ember_no-test-support-import": 1,
    "ember_no-tracked-properties-from-args": 1,
    "ember_require-computed-property-dependencies": [
      1,
      [
        {
          "name": "allowDynamicKeys",
          "value": "true"
        },
        {
          "name": "requireServiceNames",
          "value": "false"
        }
      ]
    ],
    "ember_require-return-from-computed": 1,
    "ember_require-super-in-lifecycle-hooks": [
      1,
      [
        {
          "name": "checkInitOnly",
          "value": "false"
        },
        {
          "name": "checkNativeClasses",
          "value": "true"
        }
      ]
    ],
    "ember_require-valid-css-selector-in-test-helpers": 1,
    "@eslint/fixer-return": 1,
    "@eslint/no-deprecated-context-methods": 1,
    "@eslint/no-deprecated-report-api": 1,
    "@eslint/no-identical-tests": 1,
    "@eslint/no-missing-message-ids": 1,
    "@eslint/no-missing-placeholders": 1,
    "@eslint/no-only-tests": 1,
    "@eslint/no-unused-message-ids": 1,
    "@eslint/no-unused-placeholders": 1,
    "@eslint/no-useless-token-range": 1,
    "@eslint/prefer-message-ids": 1,
    "@eslint/prefer-object-rule": 1,
    "@eslint/prefer-output-null": 1,
    "@eslint/require-meta-fixable": [
      1,
      [
        {
          "name": "catchNoFixerButFixableProperty",
          "value": "false"
        }
      ]
    ],
    "@eslint/require-meta-has-suggestions": 1,
    "@eslint/require-meta-schema": [
      1,
      [
        {
          "name": "requireSchemaPropertyWhenOptionless",
          "value": "true"
        }
      ]
    ],
    "@eslint/require-meta-type": 1,
    "es-x_no-accessor-properties": 1,
    "es-x_no-arbitrary-module-namespace-names": 1,
    "es-x_no-arraybuffer-prototype-transfer": 1,
    "es-x_no-array-from": 1,
    "es-x_no-array-isarray": 1,
    "es-x_no-array-of": 1,
    "es-x_no-array-prototype-at": 1,
    "es-x_no-array-prototype-copywithin": 1,
    "es-x_no-array-prototype-entries": 1,
    "es-x_no-array-prototype-every": 1,
    "es-x_no-array-prototype-fill": 1,
    "es-x_no-array-prototype-filter": 1,
    "es-x_no-array-prototype-find": 1,
    "es-x_no-array-prototype-findindex": 1,
    "es-x_no-array-prototype-findlast-findlastindex": 1,
    "es-x_no-array-prototype-flat": 1,
    "es-x_no-array-prototype-foreach": 1,
    "es-x_no-array-prototype-includes": 1,
    "es-x_no-array-prototype-indexof": 1,
    "es-x_no-array-prototype-keys": 1,
    "es-x_no-array-prototype-lastindexof": 1,
    "es-x_no-array-prototype-map": 1,
    "es-x_no-array-prototype-reduce": 1,
    "es-x_no-array-prototype-reduceright": 1,
    "es-x_no-array-prototype-some": 1,
    "es-x_no-array-prototype-toreversed": 1,
    "es-x_no-array-prototype-tosorted": 1,
    "es-x_no-array-prototype-tospliced": 1,
    "es-x_no-array-prototype-values": 1,
    "es-x_no-array-prototype-with": 1,
    "es-x_no-arrow-functions": 1,
    "es-x_no-async-functions": 1,
    "es-x_no-async-iteration": 1,
    "es-x_no-atomics": 1,
    "es-x_no-atomics-waitasync": 1,
    "es-x_no-bigint": 1,
    "es-x_no-binary-numeric-literals": 1,
    "es-x_no-block-scoped-functions": 1,
    "es-x_no-block-scoped-variables": 1,
    "es-x_no-classes": 1,
    "es-x_no-class-instance-fields": 1,
    "es-x_no-class-private-fields": 1,
    "es-x_no-class-private-methods": 1,
    "es-x_no-class-static-block": 1,
    "es-x_no-class-static-fields": 1,
    "es-x_no-computed-properties": 1,
    "es-x_no-date-now": 1,
    "es-x_no-date-prototype-getyear-setyear": 1,
    "es-x_no-date-prototype-togmtstring": 1,
    "es-x_no-default-parameters": 1,
    "es-x_no-destructuring": 1,
    "es-x_no-dynamic-import": 1,
    "es-x_no-error-cause": 1,
    "es-x_no-escape-unescape": 1,
    "es-x_no-exponential-operators": 1,
    "es-x_no-export-ns-from": 1,
    "es-x_no-for-of-loops": 1,
    "es-x_no-function-declarations-in-if-statement-clauses-without-block": 1,
    "es-x_no-function-prototype-bind": 1,
    "es-x_no-generators": 1,
    "es-x_no-global-this": 1,
    "es-x_no-hashbang": 1,
    "es-x_no-import-meta": 1,
    "es-x_no-initializers-in-for-in": 1,
    "es-x_no-intl-datetimeformat-prototype-formatrange": 1,
    "es-x_no-intl-datetimeformat-prototype-formattoparts": 1,
    "es-x_no-intl-displaynames": 1,
    "es-x_no-intl-getcanonicallocales": 1,
    "es-x_no-intl-listformat": 1,
    "es-x_no-intl-locale": 1,
    "es-x_no-intl-numberformat-prototype-formatrange": 1,
    "es-x_no-intl-numberformat-prototype-formatrangetoparts": 1,
    "es-x_no-intl-numberformat-prototype-formattoparts": 1,
    "es-x_no-intl-pluralrules": 1,
    "es-x_no-intl-pluralrules-prototype-selectrange": 1,
    "es-x_no-intl-relativetimeformat": 1,
    "es-x_no-intl-segmenter": 1,
    "es-x_no-intl-supportedvaluesof": 1,
    "es-x_no-json": 1,
    "es-x_no-json-superset": 1,
    "es-x_no-keyword-properties": 1,
    "es-x_no-labelled-function-declarations": 1,
    "es-x_no-legacy-object-prototype-accessor-methods": 1,
    "es-x_no-logical-assignment-operators": 1,
    "es-x_no-malformed-template-literals": 1,
    "es-x_no-map": 1,
    "es-x_no-map-groupby": 1,
    "es-x_no-math-asinh": 1,
    "es-x_no-math-atanh": 1,
    "es-x_no-math-cbrt": 1,
    "es-x_no-math-clz32": 1,
    "es-x_no-math-cosh": 1,
    "es-x_no-math-expm1": 1,
    "es-x_no-math-fround": 1,
    "es-x_no-math-hypot": 1,
    "es-x_no-math-imul": 1,
    "es-x_no-math-log10": 1,
    "es-x_no-math-log1p": 1,
    "es-x_no-math-log2": 1,
    "es-x_no-math-sign": 1,
    "es-x_no-math-sinh": 1,
    "es-x_no-math-tanh": 1,
    "es-x_no-math-trunc": 1,
    "es-x_no-modules": 1,
    "es-x_no-new-target": 1,
    "es-x_no-nullish-coalescing-operators": 1,
    "es-x_no-number-epsilon": 1,
    "es-x_no-number-isfinite": 1,
    "es-x_no-number-isinteger": 1,
    "es-x_no-number-isnan": 1,
    "es-x_no-number-issafeinteger": 1,
    "es-x_no-number-maxsafeinteger": 1,
    "es-x_no-number-minsafeinteger": 1,
    "es-x_no-number-parsefloat": 1,
    "es-x_no-number-parseint": 1,
    "es-x_no-numeric-separators": 1,
    "es-x_no-object-assign": 1,
    "es-x_no-object-create": 1,
    "es-x_no-object-defineproperties": 1,
    "es-x_no-object-defineproperty": 1,
    "es-x_no-object-entries": 1,
    "es-x_no-object-freeze": 1,
    "es-x_no-object-fromentries": 1,
    "es-x_no-object-getownpropertydescriptor": 1,
    "es-x_no-object-getownpropertydescriptors": 1,
    "es-x_no-object-getownpropertynames": 1,
    "es-x_no-object-getownpropertysymbols": 1,
    "es-x_no-object-getprototypeof": 1,
    "es-x_no-object-groupby": 1,
    "es-x_no-object-hasown": 1,
    "es-x_no-object-is": 1,
    "es-x_no-object-isextensible": 1,
    "es-x_no-object-isfrozen": 1,
    "es-x_no-object-issealed": 1,
    "es-x_no-object-keys": 1,
    "es-x_no-object-preventextensions": 1,
    "es-x_no-object-seal": 1,
    "es-x_no-object-setprototypeof": 1,
    "es-x_no-object-super-properties": 1,
    "es-x_no-object-values": 1,
    "es-x_no-octal-numeric-literals": 1,
    "es-x_no-optional-catch-binding": 1,
    "es-x_no-optional-chaining": 1,
    "es-x_no-private-in": 1,
    "es-x_no-promise": 1,
    "es-x_no-promise-all-settled": 1,
    "es-x_no-promise-any": 1,
    "es-x_no-promise-prototype-finally": 1,
    "es-x_no-promise-withresolvers": 1,
    "es-x_no-property-shorthands": 1,
    "es-x_no-proxy": 1,
    "es-x_no-reflect": 1,
    "es-x_no-regexp-d-flag": 1,
    "es-x_no-regexp-duplicate-named-capturing-groups": 1,
    "es-x_no-regexp-lookbehind-assertions": 1,
    "es-x_no-regexp-named-capture-groups": 1,
    "es-x_no-regexp-prototype-compile": 1,
    "es-x_no-regexp-prototype-flags": 1,
    "es-x_no-regexp-s-flag": 1,
    "es-x_no-regexp-u-flag": 1,
    "es-x_no-regexp-unicode-property-escapes": 1,
    "es-x_no-regexp-unicode-property-escapes-2019": 1,
    "es-x_no-regexp-unicode-property-escapes-2020": 1,
    "es-x_no-regexp-unicode-property-escapes-2021": 1,
    "es-x_no-regexp-unicode-property-escapes-2022": 1,
    "es-x_no-regexp-unicode-property-escapes-2023": 1,
    "es-x_no-regexp-v-flag": 1,
    "es-x_no-regexp-y-flag": 1,
    "es-x_no-resizable-and-growable-arraybuffers": 1,
    "es-x_no-rest-parameters": 1,
    "es-x_no-rest-spread-properties": 1,
    "es-x_no-set": 1,
    "es-x_no-set-prototype-difference": 1,
    "es-x_no-set-prototype-intersection": 1,
    "es-x_no-set-prototype-isdisjointfrom": 1,
    "es-x_no-set-prototype-issubsetof": 1,
    "es-x_no-set-prototype-issupersetof": 1,
    "es-x_no-set-prototype-symmetricdifference": 1,
    "es-x_no-set-prototype-union": 1,
    "es-x_no-shadow-catch-param": 1,
    "es-x_no-shared-array-buffer": 1,
    "es-x_no-spread-elements": 1,
    "es-x_no-string-create-html-methods": 1,
    "es-x_no-string-fromcodepoint": 1,
    "es-x_no-string-prototype-at": 1,
    "es-x_no-string-prototype-codepointat": 1,
    "es-x_no-string-prototype-includes": 1,
    "es-x_no-string-prototype-iswellformed": 1,
    "es-x_no-string-prototype-matchall": 1,
    "es-x_no-string-prototype-normalize": 1,
    "es-x_no-string-prototype-padstart-padend": 1,
    "es-x_no-string-prototype-repeat": 1,
    "es-x_no-string-prototype-replaceall": 1,
    "es-x_no-string-prototype-startswith": 1,
    "es-x_no-string-prototype-substr": 1,
    "es-x_no-string-prototype-towellformed": 1,
    "es-x_no-string-prototype-trim": 1,
    "es-x_no-string-prototype-trimleft-trimright": 1,
    "es-x_no-string-prototype-trimstart-trimend": 1,
    "es-x_no-string-raw": 1,
    "es-x_no-subclassing-builtins": 1,
    "es-x_no-symbol": 1,
    "es-x_no-symbol-prototype-description": 1,
    "es-x_no-template-literals": 1,
    "es-x_no-top-level-await": 1,
    "es-x_no-trailing-commas": 1,
    "es-x_no-trailing-function-commas": 1,
    "es-x_no-typed-arrays": 1,
    "es-x_no-unicode-codepoint-escapes": 1,
    "es-x_no-weak-map": 1,
    "es-x_no-weakrefs": 1,
    "es-x_no-weak-set": 1,
    "for-direction": 1,
    "getter-return": 1,
    "import_default": 1,
    "import_export": 1,
    "import_named": 1,
    "import_namespace": [
      1,
      [
        {
          "name": "allowComputed",
          "value": "false"
        }
      ]
    ],
    "import_no-duplicates": 1,
    "import_no-extraneous-dependencies": 1,
    "import_no-import-module-exports": 1,
    "import_no-named-as-default": 1,
    "import_no-self-import": 1,
    "import_no-unresolved": [
      1,
      [
        {
          "name": "caseSensitive",
          "value": "true"
        },
        {
          "name": "caseSensitiveStrict",
          "value": "false"
        }
      ]
    ],
    "import_no-webpack-loader-syntax": 1,
    "jest_no-conditional-expect": 1,
    "jest_no-conditional-in-test": 1,
    "jest_no-confusing-set-timeout": 1,
    "jest_no-interpolation-in-snapshots": 1,
    "jest_no-mocks-import": 1,
    "jest_prefer-importing-jest-globals": 1,
    "jest_valid-describe-callback": 1,
    "jsonc_no-bigint-literals": 1,
    "jsonc_no-binary-expression": 1,
    "jsonc_no-binary-numeric-literals": 1,
    "jsonc_no-comments": 1,
    "jsonc_no-dupe-keys": 1,
    "jsonc_no-escape-sequence-in-identifier": 1,
    "jsonc_no-hexadecimal-numeric-literals": 1,
    "jsonc_no-infinity": 1,
    "jsonc_no-irregular-whitespace": 1,
    "jsonc_no-nan": 1,
    "jsonc_no-number-props": 1,
    "jsonc_no-numeric-separators": 1,
    "jsonc_no-octal-numeric-literals": 1,
    "jsonc_no-parenthesized": 1,
    "jsonc_no-plus-sign": 1,
    "jsonc_no-regexp-literals": 1,
    "jsonc_no-sparse-arrays": 1,
    "jsonc_no-template-literals": 1,
    "jsonc_no-undefined-value": 1,
    "jsonc_no-unicode-codepoint-escapes": 1,
    "jsonc_valid-json-number": 1,
    "jsonc_vue-custom-block_no-parsing-error": 1,
    "lodash_callback-binding": 1,
    "lodash_chaining": 1,
    "lodash_chain-style": 1,
    "lodash_collection-method-value": 1,
    "lodash_collection-ordering": 1,
    "lodash_collection-return": 1,
    "lodash_consistent-compose": 1,
    "lodash_identity-shorthand": 1,
    "lodash_import-scope": 1,
    "lodash_matches-prop-shorthand": 1,
    "lodash_matches-shorthand": 1,
    "lodash_no-commit": 1,
    "lodash_no-double-unwrap": 1,
    "lodash_no-extra-args": 1,
    "lodash_no-unbound-this": 1,
    "lodash_path-style": 1,
    "lodash_prefer-compact": 1,
    "lodash_prefer-constant": 1,
    "lodash_prefer-filter": 1,
    "lodash_prefer-find": 1,
    "lodash_prefer-flat-map": 1,
    "lodash_prefer-get": 1,
    "lodash_prefer-immutable-method": 1,
    "lodash_prefer-includes": 1,
    "lodash_prefer-invoke-map": 1,
    "lodash_prefer-is-nil": 1,
    "lodash_prefer-lodash-chain": 1,
    "lodash_prefer-lodash-method": 1,
    "lodash_prefer-lodash-typecheck": 1,
    "lodash_prefer-map": 1,
    "lodash_prefer-matches": 1,
    "lodash_prefer-noop": 1,
    "lodash_prefer-over-quantifier": 1,
    "lodash_preferred-alias": 1,
    "lodash_prefer-reject": 1,
    "lodash_prefer-some": 1,
    "lodash_prefer-startswith": 1,
    "lodash_prefer-thru": 1,
    "lodash_prefer-times": 1,
    "lodash_prefer-wrapper-method": 1,
    "lodash_prop-shorthand": 1,
    "lodash_unwrap": 1,
    "@lwc_lwc_no-attributes-during-construction": 1,
    "@lwc_lwc_no-unsupported-ssr-properties": 1,
    "mocha_handle-done-callback": [
      1,
      [
        {
          "name": "ignoreSkipped",
          "value": "false"
        }
      ]
    ],
    "mocha_no-async-describe": 1,
    "mocha_no-exclusive-tests": 1,
    "mocha_no-nested-tests": 1,
    "mocha_no-return-and-callback": 1,
    "mocha_no-skipped-tests": 1,
    "mocha_no-top-level-hooks": 1,
    "n_hashbang": 1,
    "n_no-callback-literal": 1,
    "n_no-deprecated-api": 1,
    "n_no-exports-assign": 1,
    "n_no-extraneous-import": 1,
    "n_no-extraneous-require": 1,
    "n_no-missing-import": [
      1,
      [
        {
          "name": "ignoreTypeImport",
          "value": "false"
        }
      ]
    ],
    "n_no-missing-require": 1,
    "n_no-unpublished-bin": 1,
    "n_no-unpublished-import": [
      1,
      [
        {
          "name": "ignoreTypeImport",
          "value": "false"
        },
        {
          "name": "ignorePrivate",
          "value": "true"
        }
      ]
    ],
    "n_no-unpublished-require": [
      1,
      [
        {
          "name": "ignorePrivate",
          "value": "true"
        }
      ]
    ],
    "n_no-unsupported-features_es-builtins": 1,
    "n_no-unsupported-features_es-syntax": 1,
    "n_no-unsupported-features_node-builtins": 1,
    "no-async-promise-executor": 1,
    "no-await-in-loop": 1,
    "no-buffer-constructor": 1,
    "no-case-declarations": 1,
    "no-class-assign": 1,
    "no-compare-neg-zero": 1,
    "no-cond-assign": [
      1,
      [
        {
          "name": "unnamedParam",
          "value": "except-parens"
        }
      ]
    ],
    "no-constant-binary-expression": 1,
    "no-constant-condition": 1,
    "no-const-assign": 1,
    "no-constructor-return": 1,
    "no-control-regex": 1,
    "no-debugger": 1,
    "no-delete-var": 1,
    "no-dupe-args": 1,
    "no-dupe-class-members": 1,
    "no-dupe-else-if": 1,
    "no-dupe-keys": 1,
    "no-duplicate-case": 1,
    "no-duplicate-imports": 1,
    "no-empty": 1,
    "no-empty-character-class": 1,
    "no-empty-pattern": 1,
    "no-empty-static-block": 1,
    "no-ex-assign": 1,
    "no-extra-boolean-cast": 1,
    "no-fallthrough": 1,
    "no-func-assign": 1,
    "no-global-assign": 1,
    "no-import-assign": 1,
    "no-inner-declarations": [
      1,
      [
        {
          "name": "unnamedParam",
          "value": "functions"
        }
      ]
    ],
    "no-invalid-regexp": 1,
    "no-irregular-whitespace": 1,
    "no-loss-of-precision": 1,
    "no-negated-in-lhs": 1,
    "no-new-native-nonconstructor": 1,
    "no-new-symbol": 1,
    "no-nonoctal-decimal-escape": 1,
    "no-obj-calls": 1,
    "no-octal": 1,
    "no-promise-executor-return": 1,
    "no-prototype-builtins": 1,
    "no-redeclare": 1,
    "no-regex-spaces": 1,
    "no-self-assign": 1,
    "no-self-compare": 1,
    "no-setter-return": 1,
    "no-shadow-restricted-names": 1,
    "no-sparse-arrays": 1,
    "no-template-curly-in-string": 1,
    "no-this-before-super": 1,
    "no-undef": 1,
    "no-unexpected-multiline": 1,
    "no-unmodified-loop-condition": 1,
    "no-unreachable": 1,
    "no-unreachable-loop": 1,
    "no-unsafe-finally": 1,
    "no-unsafe-negation": 1,
    "no-unsafe-optional-chaining": 1,
    "no-unused-labels": 1,
    "no-unused-private-class-members": 1,
    "no-unused-vars": 1,
    "no-use-before-define": 1,
    "no-useless-assignment": 1,
    "no-useless-backreference": 1,
    "no-useless-catch": 1,
    "no-useless-escape": 1,
    "no-with": 1,
    "n_process-exit-as-throw": 1,
    "playwright_expect-expect": 1,
    "playwright_missing-playwright-await": 1,
    "playwright_no-commented-out-tests": 1,
    "playwright_no-conditional-expect": 1,
    "playwright_no-conditional-in-test": 1,
    "playwright_no-eval": 1,
    "playwright_no-focused-test": 1,
    "playwright_no-nested-step": 1,
    "playwright_no-networkidle": 1,
    "playwright_no-nth-methods": 1,
    "playwright_no-page-pause": 1,
    "playwright_no-unsafe-references": 1,
    "playwright_no-useless-await": 1,
    "playwright_no-useless-not": 1,
    "playwright_valid-describe-callback": 1,
    "playwright_valid-expect": 1,
    "promise_always-return": 1,
    "promise_catch-or-return": 1,
    "promise_no-multiple-resolved": 1,
    "promise_no-new-statics": 1,
    "promise_no-return-in-finally": 1,
    "promise_spec-only": 1,
    "promise_valid-params": 1,
    "react_button-has-type": [
      1,
      [
        {
          "name": "button",
          "value": "true"
        },
        {
          "name": "submit",
          "value": "true"
        },
        {
          "name": "reset",
          "value": "true"
        }
      ]
    ],
    "react-hooks_rules-of-hooks": 1,
    "react_jsx-key": [
      1,
      [
        {
          "name": "checkFragmentShorthand",
          "value": "false"
        },
        {
          "name": "checkKeyMustBeforeSpread",
          "value": "false"
        },
        {
          "name": "warnOnDuplicates",
          "value": "false"
        }
      ]
    ],
    "react_jsx-no-comment-textnodes": 1,
    "react_jsx-no-duplicate-props": 1,
    "react_jsx-no-leaked-render": [
      1,
      [
        {
          "name": "validStrategies",
          "value": "[\"ternary\",\"coerce\"]"
        }
      ]
    ],
    "react_jsx-no-undef": 1,
    "react_no-access-state-in-setstate": 1,
    "react_no-danger-with-children": 1,
    "react_no-direct-mutation-state": 1,
    "react_no-namespace": 1,
    "react_no-redundant-should-component-update": 1,
    "react_no-this-in-sfc": 1,
    "react_no-unescaped-entities": 1,
    "react_no-unknown-property": [
      1,
      [
        {
          "name": "requireDataLowercase",
          "value": "false"
        }
      ]
    ],
    "react_no-unstable-nested-components": 1,
    "react_prefer-exact-props": 1,
    "react_react-in-jsx-scope": 1,
    "react_require-render-return": 1,
    "react_style-prop-object": 1,
    "redux-saga_no-unhandled-errors": 1,
    "redux-saga_no-yield-in-race": 1,
    "redux-saga_yield-effects": 1,
    "regexp_confusing-quantifier": 1,
    "regexp_no-contradiction-with-assertion": 1,
    "regexp_no-empty-alternative": 1,
    "regexp_no-invalid-regexp": 1,
    "regexp_no-lazy-ends": 1,
    "regexp_no-misleading-capturing-group": 1,
    "regexp_no-misleading-unicode-character": 1,
    "regexp_no-missing-g-flag": 1,
    "regexp_no-optional-assertion": 1,
    "regexp_no-potentially-useless-backreference": 1,
    "regexp_no-super-linear-backtracking": 1,
    "regexp_no-super-linear-move": 1,
    "regexp_no-useless-assertions": 1,
    "regexp_optimal-lookaround-quantifier": 1,
    "require-atomic-updates": 1,
    "require-yield": 1,
    "security_detect-bidi-characters": 1,
    "security_detect-buffer-noassert": 1,
    "security_detect-child-process": 1,
    "security_detect-disable-mustache-escape": 1,
    "security_detect-eval-with-expression": 1,
    "security_detect-new-buffer": 1,
    "security_detect-no-csrf-before-method-override": 1,
    "security_detect-non-literal-fs-filename": 1,
    "security_detect-non-literal-regexp": 1,
    "security_detect-non-literal-require": 1,
    "security_detect-object-injection": 1,
    "security_detect-possible-timing-attacks": 1,
    "security_detect-pseudoRandomBytes": 1,
    "security_detect-unsafe-regex": 1,
    "security-node_detect-absence-of-name-option-in-exrpress-session": 1,
    "security-node_detect-child-process": 1,
    "security-node_detect-dangerous-redirects": 1,
    "security-node_detect-eval-with-expr": 1,
    "security-node_detect-html-injection": 1,
    "security-node_detect-improper-exception-handling": 1,
    "security-node_detect-non-literal-require-calls": 1,
    "security-node_detect-nosql-injection": 1,
    "security-node_detect-option-multiplestatements-in-mysql": 1,
    "security-node_detect-option-rejectunauthorized-in-nodejs-httpsrequest": 1,
    "security-node_detect-option-unsafe-in-serialize-javascript-npm-package": 1,
    "security-node_detect-possible-timing-attacks": 1,
    "security-node_detect-security-missconfiguration-cookie": 1,
    "security-node_detect-unhandled-async-errors": 1,
    "security-node_detect-unhandled-event-errors": 1,
    "security-node_disable-ssl-across-node-server": 1,
    "security-node_non-literal-reg-expr": 1,
    "@shopify_react-initialize-state": 1,
    "@shopify_react-type-state": 1,
    "sonarjs_anchor-precedence": 1,
    "sonarjs_array-callback-without-return": 1,
    "sonarjs_aws-apigateway-public-api": 1,
    "sonarjs_aws-ec2-rds-dms-public": 1,
    "sonarjs_aws-ec2-unencrypted-ebs-volume": 1,
    "sonarjs_aws-efs-unencrypted": 1,
    "sonarjs_aws-iam-all-privileges": 1,
    "sonarjs_aws-iam-all-resources-accessible": 1,
    "sonarjs_aws-iam-privilege-escalation": 1,
    "sonarjs_aws-iam-public-access": 1,
    "sonarjs_aws-opensearchservice-domain": 1,
    "sonarjs_aws-rds-unencrypted-databases": 1,
    "sonarjs_aws-restricted-ip-admin-access": 1,
    "sonarjs_aws-s3-bucket-granted-access": 1,
    "sonarjs_aws-s3-bucket-insecure-http": 1,
    "sonarjs_aws-s3-bucket-public-access": 1,
    "sonarjs_aws-s3-bucket-versioning": 1,
    "sonarjs_aws-sagemaker-unencrypted-notebook": 1,
    "sonarjs_aws-sns-unencrypted-topics": 1,
    "sonarjs_aws-sqs-unencrypted-queue": 1,
    "sonarjs_bitwise-operators": 1,
    "sonarjs_code-eval": 1,
    "sonarjs_comma-or-logical-or-case": 1,
    "sonarjs_confidential-information-logging": 1,
    "sonarjs_constructor-for-side-effects": 1,
    "sonarjs_content-length": 1,
    "sonarjs_content-security-policy": 1,
    "sonarjs_cookie-no-httponly": 1,
    "sonarjs_cors": 1,
    "sonarjs_csrf": 1,
    "sonarjs_different-types-comparison": 1,
    "sonarjs_disabled-auto-escaping": 1,
    "sonarjs_disabled-resource-integrity": 1,
    "sonarjs_disabled-timeout": 1,
    "sonarjs_empty-string-repetition": 1,
    "sonarjs_encryption-secure-mode": 1,
    "sonarjs_existing-groups": 1,
    "sonarjs_file-permissions": 1,
    "sonarjs_file-uploads": 1,
    "sonarjs_for-in": 1,
    "sonarjs_for-loop-increment-sign": 1,
    "sonarjs_frame-ancestors": 1,
    "sonarjs_generator-without-yield": 1,
    "sonarjs_hashing": 1,
    "sonarjs_hidden-files": 1,
    "sonarjs_in-operator-type-error": 1,
    "sonarjs_insecure-cookie": 1,
    "sonarjs_insecure-jwt-token": 1,
    "sonarjs_jsx-no-leaked-render": 1,
    "sonarjs_link-with-target-blank": 1,
    "sonarjs_new-operator-misuse": 1,
    "sonarjs_no-all-duplicated-branches": 1,
    "sonarjs_no-alphabetical-sort": 1,
    "sonarjs_no-angular-bypass-sanitization": 1,
    "sonarjs_no-built-in-override": 1,
    "sonarjs_no-clear-text-protocols": 1,
    "sonarjs_no-collection-size-mischeck": 1,
    "sonarjs_no-control-regex": 1,
    "sonarjs_no-delete-var": 1,
    "sonarjs_no-element-overwrite": 1,
    "sonarjs_no-empty-alternatives": 1,
    "sonarjs_no-empty-character-class": 1,
    "sonarjs_no-empty-collection": 1,
    "sonarjs_no-exclusive-tests": 1,
    "sonarjs_no-extra-arguments": 1,
    "sonarjs_no-function-declaration-in-block": 1,
    "sonarjs_no-globals-shadowing": 1,
    "sonarjs_no-hardcoded-ip": 1,
    "sonarjs_no-hardcoded-passwords": 1,
    "sonarjs_no-hardcoded-secrets": 1,
    "sonarjs_no-hook-setter-in-body": 1,
    "sonarjs_no-identical-conditions": 1,
    "sonarjs_no-identical-expressions": 1,
    "sonarjs_no-ignored-return": 1,
    "sonarjs_no-intrusive-permissions": 1,
    "sonarjs_no-invalid-regexp": 1,
    "sonarjs_no-ip-forward": 1,
    "sonarjs_no-literal-call": 1,
    "sonarjs_no-mime-sniff": 1,
    "sonarjs_no-misleading-character-class": 1,
    "sonarjs_no-mixed-content": 1,
    "sonarjs_non-existent-operator": 1,
    "sonarjs_no-one-iteration-loop": 1,
    "sonarjs_no-os-command-from-path": 1,
    "sonarjs_no-parameter-reassignment": 1,
    "sonarjs_no-reference-error": 1,
    "sonarjs_no-referrer-policy": 1,
    "sonarjs_no-same-argument-assert": 1,
    "sonarjs_no-try-promise": 1,
    "sonarjs_no-unsafe-unzip": 1,
    "sonarjs_no-unthrown-error": 1,
    "sonarjs_no-useless-increment": 1,
    "sonarjs_no-useless-intersection": 1,
    "sonarjs_no-useless-react-setstate": 1,
    "sonarjs_no-use-of-empty-return-value": 1,
    "sonarjs_no-weak-cipher": 1,
    "sonarjs_no-weak-keys": 1,
    "sonarjs_null-dereference": 1,
    "sonarjs_os-command": 1,
    "sonarjs_post-message": 1,
    "sonarjs_production-debug": 1,
    "sonarjs_pseudo-random": 1,
    "sonarjs_publicly-writable-directories": 1,
    "sonarjs_reduce-initial-value": 1,
    "sonarjs_session-regeneration": 1,
    "sonarjs_slow-regex": 1,
    "sonarjs_sql-queries": 1,
    "sonarjs_stateful-regex": 1,
    "sonarjs_strict-transport-security": 1,
    "sonarjs_super-invocation": 1,
    "sonarjs_table-header": 1,
    "sonarjs_table-header-reference": 1,
    "sonarjs_unicode-aware-regex": 1,
    "sonarjs_unverified-certificate": 1,
    "sonarjs_unverified-hostname": 1,
    "sonarjs_updated-const-var": 1,
    "sonarjs_weak-ssl": 1,
    "sonarjs_xml-parser-xxe": 1,
    "sonarjs_x-powered-by": 1,
    "storybook_await-interactions": 1,
    "storybook_context-in-play-function": 1,
    "storybook_default-exports": 1,
    "storybook_hierarchy-separator": 1,
    "storybook_meta-inline-properties": 1,
    "storybook_no-stories-of": 1,
    "storybook_no-title-property-in-meta": 1,
    "storybook_no-uninstalled-addons": 1,
    "storybook_story-exports": 1,
    "suitescript_api-version": 1,
    "suitescript_entry-points": 1,
    "suitescript_no-extra-modules": 1,
    "suitescript_no-invalid-modules": 1,
    "suitescript_no-module-extensions": 1,
    "suitescript_script-type": 1,
    "svelte_comment-directive": 1,
    "svelte_no-at-debug-tags": 1,
    "svelte_no-dom-manipulating": 1,
    "svelte_no-dupe-else-if-blocks": 1,
    "svelte_no-dupe-on-directives": 1,
    "svelte_no-dupe-style-properties": 1,
    "svelte_no-dupe-use-directives": 1,
    "svelte_no-export-load-in-svelte-module-in-kit-pages": 1,
    "svelte_no-ignored-unsubscribe": 1,
    "svelte_no-inner-declarations": 1,
    "svelte_no-not-function-handler": 1,
    "svelte_no-object-in-text-mustaches": 1,
    "svelte_no-raw-special-elements": 1,
    "svelte_no-reactive-reassign": 1,
    "svelte_no-shorthand-style-property-overrides": 1,
    "svelte_no-store-async": 1,
    "svelte_no-svelte-internal": 1,
    "svelte_no-target-blank": 1,
    "svelte_no-unknown-style-directive-property": 1,
    "svelte_require-store-reactive-access": 1,
    "svelte_system": 1,
    "svelte_valid-compile": 1,
    "svelte_valid-prop-names-in-kit-pages": 1,
    "svelte_valid-style-parse": 1,
    "tailwindcss_migration-from-tailwind-2": 1,
    "tailwindcss_no-contradicting-classname": 1,
    "@tanstack_query_exhaustive-deps": 1,
    "@tanstack_query_infinite-query-property-order": 1,
    "@tanstack_query_no-rest-destructuring": 1,
    "@tanstack_query_no-unstable-deps": 1,
    "@tanstack_query_stable-query-client": 1,
    "testing-library_await-async-events": [
      1,
      [
        {
          "name": "eventModule",
          "value": "userEvent"
        }
      ]
    ],
    "testing-library_await-async-queries": 1,
    "testing-library_await-async-utils": 1,
    "testing-library_no-await-sync-events": [
      1,
      [
        {
          "name": "eventModules",
          "value": "[\"fire-event\"]"
        }
      ]
    ],
    "testing-library_no-await-sync-queries": 1,
    "testing-library_no-container": 1,
    "testing-library_no-debugging-utils": 1,
    "testing-library_no-dom-import": 1,
    "testing-library_no-manual-cleanup": 1,
    "testing-library_no-node-access": 1,
    "testing-library_no-promise-in-fire-event": 1,
    "testing-library_no-render-in-lifecycle": 1,
    "testing-library_no-unnecessary-act": 1,
    "testing-library_no-wait-for-snapshot": 1,
    "testing-library_prefer-query-by-disappearance": 1,
    "test-selectors_anchor": 1,
    "test-selectors_button": 1,
    "test-selectors_input": 1,
    "test-selectors_onChange": 1,
    "test-selectors_onClick": 1,
    "test-selectors_onKeyDown": 1,
    "test-selectors_onKeyUp": 1,
    "test-selectors_onSubmit": 1,
    "@typescript-eslint_adjacent-overload-signatures": 1,
    "@typescript-eslint_array-type": 1,
    "@typescript-eslint_await-thenable": 1,
    "@typescript-eslint_ban-ts-comment": [
      1,
      [
        {
          "name": "minimumDescriptionLength",
          "value": "3"
        }
      ]
    ],
    "@typescript-eslint_ban-tslint-comment": 1,
    "@typescript-eslint_class-literal-property-style": 1,
    "@typescript-eslint_consistent-generic-constructors": 1,
    "@typescript-eslint_consistent-indexed-object-style": 1,
    "@typescript-eslint_consistent-type-assertions": 1,
    "@typescript-eslint_consistent-type-definitions": 1,
    "@typescript-eslint_dot-notation": [
      1,
      [
        {
          "name": "allowKeywords",
          "value": "true"
        },
        {
          "name": "allowPattern",
          "value": ""
        },
        {
          "name": "allowProtectedClassPropertyAccess",
          "value": "false"
        },
        {
          "name": "allowPrivateClassPropertyAccess",
          "value": "false"
        },
        {
          "name": "allowIndexSignaturePropertyAccess",
          "value": "false"
        }
      ]
    ],
    "@typescript-eslint_explicit-function-return-type": 1,
    "@typescript-eslint_explicit-member-accessibility": 1,
    "@typescript-eslint_explicit-module-boundary-types": 1,
    "@typescript-eslint_no-array-constructor": 1,
    "@typescript-eslint_no-array-delete": 1,
    "@typescript-eslint_no-base-to-string": 1,
    "@typescript-eslint_no-confusing-non-null-assertion": 1,
    "@typescript-eslint_no-confusing-void-expression": 1,
    "@typescript-eslint_no-deprecated": 1,
    "@typescript-eslint_no-dupe-class-members": 1,
    "@typescript-eslint_no-duplicate-enum-values": 1,
    "@typescript-eslint_no-duplicate-type-constituents": 1,
    "@typescript-eslint_no-dynamic-delete": 1,
    "@typescript-eslint_no-empty-function": 1,
    "@typescript-eslint_no-empty-object-type": 1,
    "@typescript-eslint_no-explicit-any": 1,
    "@typescript-eslint_no-extraneous-class": 1,
    "@typescript-eslint_no-extra-non-null-assertion": 1,
    "@typescript-eslint_no-floating-promises": 1,
    "@typescript-eslint_no-for-in-array": 1,
    "@typescript-eslint_no-implied-eval": 1,
    "@typescript-eslint_no-import-type-side-effects": 1,
    "@typescript-eslint_no-inferrable-types": 1,
    "@typescript-eslint_no-invalid-void-type": 1,
    "@typescript-eslint_no-loss-of-precision": 1,
    "@typescript-eslint_no-meaningless-void-operator": [
      1,
      [
        {
          "name": "checkNever",
          "value": "false"
        }
      ]
    ],
    "@typescript-eslint_no-misused-new": 1,
    "@typescript-eslint_no-misused-promises": 1,
    "@typescript-eslint_no-misused-spread": 1,
    "@typescript-eslint_no-mixed-enums": 1,
    "@typescript-eslint_no-namespace": 1,
    "@typescript-eslint_non-nullable-type-assertion-style": 1,
    "@typescript-eslint_no-non-null-asserted-nullish-coalescing": 1,
    "@typescript-eslint_no-non-null-asserted-optional-chain": 1,
    "@typescript-eslint_no-non-null-assertion": 1,
    "@typescript-eslint_no-redundant-type-constituents": 1,
    "@typescript-eslint_no-require-imports": 1,
    "@typescript-eslint_no-this-alias": 1,
    "@typescript-eslint_no-unnecessary-boolean-literal-compare": 1,
    "@typescript-eslint_no-unnecessary-condition": 1,
    "@typescript-eslint_no-unnecessary-template-expression": 1,
    "@typescript-eslint_no-unnecessary-type-arguments": 1,
    "@typescript-eslint_no-unnecessary-type-assertion": 1,
    "@typescript-eslint_no-unnecessary-type-constraint": 1,
    "@typescript-eslint_no-unnecessary-type-parameters": 1,
    "@typescript-eslint_no-unused-expressions": 1,
    "@typescript-eslint_no-unused-vars": 1,
    "@typescript-eslint_no-use-before-define": 1,
    "@typescript-eslint_no-useless-constructor": 1,
    "@typescript-eslint_no-var-requires": 1,
    "@typescript-eslint_no-wrapper-object-types": 1,
    "@typescript-eslint_only-throw-error": 1,
    "@typescript-eslint_parameter-properties": 1,
    "@typescript-eslint_prefer-as-const": 1,
    "@typescript-eslint_prefer-find": 1,
    "@typescript-eslint_prefer-for-of": 1,
    "@typescript-eslint_prefer-function-type": 1,
    "@typescript-eslint_prefer-includes": 1,
    "@typescript-eslint_prefer-literal-enum-member": 1,
    "@typescript-eslint_prefer-namespace-keyword": 1,
    "@typescript-eslint_prefer-nullish-coalescing": 1,
    "@typescript-eslint_prefer-optional-chain": 1,
    "@typescript-eslint_prefer-promise-reject-errors": 1,
    "@typescript-eslint_prefer-reduce-type-parameter": 1,
    "@typescript-eslint_prefer-regexp-exec": 1,
    "@typescript-eslint_prefer-return-this-type": 1,
    "@typescript-eslint_prefer-string-starts-ends-with": 1,
    "@typescript-eslint_prefer-ts-expect-error": 1,
    "@typescript-eslint_related-getter-setter-pairs": 1,
    "@typescript-eslint_require-array-sort-compare": 1,
    "@typescript-eslint_require-await": 1,
    "@typescript-eslint_restrict-plus-operands": 1,
    "@typescript-eslint_restrict-template-expressions": 1,
    "@typescript-eslint_return-await": 1,
    "@typescript-eslint_triple-slash-reference": 1,
    "@typescript-eslint_unbound-method": 1,
    "@typescript-eslint_unified-signatures": 1,
    "@typescript-eslint_use-unknown-in-catch-callback-variable": 1,
    "unicorn_consistent-assert": 1,
    "unicorn_consistent-existence-index-check": 1,
    "unicorn_custom-error-definition": 1,
    "unicorn_error-message": 1,
    "unicorn_explicit-length-check": [
      1,
      [
        {
          "name": "non-zero",
          "value": "greater-than"
        }
      ]
    ],
    "unicorn_import-style": 1,
    "unicorn_no-accessor-recursion": 1,
    "unicorn_no-array-callback-reference": 1,
    "unicorn_no-document-cookie": 1,
    "unicorn_no-instanceof-builtins": 1,
    "unicorn_no-invalid-fetch-options": 1,
    "unicorn_no-invalid-remove-event-listener": 1,
    "unicorn_no-negation-in-equality-check": 1,
    "unicorn_no-new-buffer": 1,
    "unicorn_no-object-as-default-parameter": 1,
    "unicorn_no-thenable": 1,
    "unicorn_prefer-math-min-max": 1,
    "unicorn_require-post-message-target-origin": 1,
    "unused-imports_no-unused-imports": 1,
    "unused-imports_no-unused-vars": 1,
    "use-isnan": 1,
    "valid-typeof": 1,
    "@vitest_consistent-test-filename": [
      1,
      [
        {
          "name": "pattern",
          "value": ".*\\.test\\.[tj]sx?$"
        },
        {
          "name": "allTestPattern",
          "value": ".*\\.(test|spec)\\.[tj]sx?$"
        }
      ]
    ],
    "@vitest_max-nested-describe": 1,
    "@vitest_no-conditional-expect": 1,
    "@vitest_no-conditional-in-test": 1,
    "@vitest_no-conditional-tests": 1,
    "@vitest_no-focused-tests": [
      1,
      [
        {
          "name": "fixable",
          "value": "true"
        }
      ]
    ],
    "@vitest_no-identical-title": 1,
    "@vitest_no-interpolation-in-snapshots": 1,
    "@vitest_no-mocks-import": 1,
    "@vitest_no-test-return-statement": 1,
    "@vitest_prefer-lowercase-title": [
      1,
      [
        {
          "name": "ignoreTopLevelDescribe",
          "value": "false"
        },
        {
          "name": "lowercaseFirstCharacterOnly",
          "value": "true"
        }
      ]
    ],
    "@vitest_require-local-test-context-for-concurrent-snapshots": 1,
    "@vitest_valid-describe-callback": 1,
    "vue_comment-directive": 1,
    "vuejs-accessibility_alt-text": 1,
    "vuejs-accessibility_anchor-has-content": 1,
    "vuejs-accessibility_aria-props": 1,
    "vuejs-accessibility_aria-role": [
      1,
      [
        {
          "name": "ignoreNonDOM",
          "value": "true"
        }
      ]
    ],
    "vuejs-accessibility_aria-unsupported-elements": 1,
    "vuejs-accessibility_click-events-have-key-events": 1,
    "vuejs-accessibility_form-control-has-label": 1,
    "vuejs-accessibility_heading-has-content": 1,
    "vuejs-accessibility_iframe-has-title": 1,
    "vuejs-accessibility_interactive-supports-focus": 1,
    "vuejs-accessibility_label-has-for": 1,
    "vuejs-accessibility_media-has-caption": 1,
    "vuejs-accessibility_mouse-events-have-key-events": 1,
    "vuejs-accessibility_no-access-key": 1,
    "vuejs-accessibility_no-aria-hidden-on-focusable": 1,
    "vuejs-accessibility_no-autofocus": [
      1,
      [
        {
          "name": "ignoreNonDOM",
          "value": "true"
        }
      ]
    ],
    "vuejs-accessibility_no-distracting-elements": 1,
    "vuejs-accessibility_no-redundant-roles": 1,
    "vuejs-accessibility_no-role-presentation-on-focusable": 1,
    "vuejs-accessibility_no-static-element-interactions": 1,
    "vuejs-accessibility_role-has-required-aria-props": 1,
    "vuejs-accessibility_tabindex-no-positive": 1,
    "vue_jsx-uses-vars": 1,
    "vue_match-component-import-name": 1,
    "vue_max-lines-per-block": 1,
    "vue_max-props": 1,
    "vue_max-template-depth": 1,
    "vue_no-arrow-functions-in-watch": 1,
    "vue_no-async-in-computed-properties": 1,
    "vue_no-child-content": 1,
    "vue_no-computed-properties-in-data": 1,
    "vue_no-constant-condition": 1,
    "vue_no-custom-modifiers-on-v-model": 1,
    "vue_no-deprecated-data-object-declaration": 1,
    "vue_no-deprecated-delete-set": 1,
    "vue_no-deprecated-destroyed-lifecycle": 1,
    "vue_no-deprecated-dollar-listeners-api": 1,
    "vue_no-deprecated-dollar-scopedslots-api": 1,
    "vue_no-deprecated-events-api": 1,
    "vue_no-deprecated-filter": 1,
    "vue_no-deprecated-functional-template": 1,
    "vue_no-deprecated-html-element-is": 1,
    "vue_no-deprecated-inline-template": 1,
    "vue_no-deprecated-model-definition": 1,
    "vue_no-deprecated-props-default-this": 1,
    "vue_no-deprecated-router-link-tag-prop": 1,
    "vue_no-deprecated-v-bind-sync": 1,
    "vue_no-deprecated-v-on-native-modifier": 1,
    "vue_no-deprecated-v-on-number-modifiers": 1,
    "vue_no-deprecated-vue-config-keycodes": 1,
    "vue_no-dupe-keys": 1,
    "vue_no-dupe-v-else-if": 1,
    "vue_no-duplicate-attributes": 1,
    "vue_no-empty-pattern": 1,
    "vue_no-export-in-script-setup": 1,
    "vue_no-expose-after-await": 1,
    "vue_no-irregular-whitespace": [
      1,
      [
        {
          "name": "skipTemplates",
          "value": "false"
        },
        {
          "name": "skipRegExps",
          "value": "false"
        },
        {
          "name": "skipHTMLTextContents",
          "value": "false"
        },
        {
          "name": "skipComments",
          "value": "false"
        },
        {
          "name": "skipStrings",
          "value": "true"
        },
        {
          "name": "skipHTMLAttributeValues",
          "value": "false"
        }
      ]
    ],
    "vue_no-lone-template": 1,
    "vue_no-loss-of-precision": 1,
    "vue_no-multiple-slot-args": 1,
    "vue_no-multiple-template-root": 1,
    "vue_no-parsing-error": 1,
    "vue_no-ref-object-reactivity-loss": 1,
    "vue_no-required-prop-with-default": 1,
    "vue_no-reserved-props": 1,
    "vue_no-restricted-class": 1,
    "vue_no-shared-component-data": 1,
    "vue_no-side-effects-in-computed-properties": 1,
    "vue_no-sparse-arrays": 1,
    "vue_no-template-key": 1,
    "vue_no-template-target-blank": 1,
    "vue_no-textarea-mustache": 1,
    "vue_no-this-in-before-route-enter": 1,
    "vue_no-use-computed-property-like-method": 1,
    "vue_no-useless-template-attributes": 1,
    "vue_no-v-for-template-key": 1,
    "vue_no-v-for-template-key-on-child": 1,
    "vue_no-v-model-argument": 1,
    "vue_no-v-text-v-html-on-component": 1,
    "vue_prefer-prop-type-boolean-first": 1,
    "vue_require-component-is": 1,
    "vue_require-default-export": 1,
    "vue_require-explicit-slots": 1,
    "vue_require-render-return": 1,
    "vue_require-slots-as-functions": 1,
    "vue_require-toggle-inside-transition": 1,
    "vue_require-v-for-key": 1,
    "vue_restricted-component-names": 1,
    "vue_return-in-computed-property": 1,
    "vue_return-in-emits-validator": 1,
    "vue-scoped-css_no-parsing-error": 1,
    "vuetify_no-deprecated-imports": 1,
    "vue_valid-attribute-name": 1,
    "vue_valid-define-emits": 1,
    "vue_valid-define-options": 1,
    "vue_valid-define-props": 1,
    "vue_valid-model-definition": 1,
    "vue_valid-next-tick": 1,
    "vue_valid-template-root": 1,
    "vue_valid-v-bind": 1,
    "vue_valid-v-bind-sync": 1,
    "vue_valid-v-cloak": 1,
    "vue_valid-v-else": 1,
    "vue_valid-v-else-if": 1,
    "vue_valid-v-for": 1,
    "vue_valid-v-html": 1,
    "vue_valid-v-if": 1,
    "vue_valid-v-is": 1,
    "vue_valid-v-memo": 1,
    "vue_valid-v-model": 1,
    "vue_valid-v-on": 1,
    "vue_valid-v-once": 1,
    "vue_valid-v-pre": 1,
    "vue_valid-v-show": 1,
    "vue_valid-v-slot": 1,
    "vue_valid-v-text": 1,
    "vue_v-if-else-key": 1,
    "wdio_await-expect": 1,
    "wdio_no-debug": 1,
    "wdio_no-pause": 1,
    "xss_no-location-href-assign": 1,
    "yml_no-irregular-whitespace": [
      1,
      [
        {
          "name": "skipComments",
          "value": "false"
        },
        {
          "name": "skipQuotedScalars",
          "value": "true"
        }
      ]
    ],
    "yml_no-tab-indent": 1,
    "yml_vue-custom-block_no-parsing-error": 1
  }
}
