export default {
  "linterOptions": {
    "reportUnusedDisableDirectives": "error"
  },
  "files": [
    "**/*.{js,jsx,mjs,cjs,ts,tsx}"
  ],
  "ignores": [
    "**/node_modules/**",
    "dist/**"
  ],
  "languageOptions": {
    "ecmaVersion": "latest",
    "sourceType": "module",
    "parserOptions": {
      "ecmaFeatures": {
        "jsx": true
      }
    }
  },
  "rules": {
    "@angular-eslint/contextual-lifecycle": 1,
    "@angular-eslint/no-async-lifecycle-method": 1,
    "@angular-eslint/no-attribute-decorator": 1,
    "@angular-eslint/sort-lifecycle-methods": 1,
    "array-callback-return": 1,
    "ava/assertion-arguments": 1,
    "ava/no-duplicate-modifiers": 1,
    "ava/no-identical-title": 1,
    "ava/no-nested-tests": 1,
    "ava/no-unknown-modifiers": 1,
    "ava/test-title": 1,
    "ava/use-t-throws-async-well": 1,
    "ava/use-t-well": 1,
    "compat/compat": 1,
    "constructor-super": 1,
    "cypress/assertion-before-screenshot": 1,
    "cypress/no-assigning-return-values": 1,
    "cypress/no-async-before": 1,
    "cypress/no-async-tests": 1,
    "cypress/no-unnecessary-waiting": 1,
    "cypress/unsafe-to-chain-command": [
      1,
      {
        "methods": []
      }
    ],
    "ember/avoid-leaking-state-in-ember-objects": 1,
    "ember/classic-decorator-hooks": 1,
    "ember/classic-decorator-no-classic-methods": 1,
    "ember/jquery-ember-run": 1,
    "ember/new-module-imports": 1,
    "ember/no-arrow-function-computed-properties": [
      1,
      {
        "onlyThisContexts": false
      }
    ],
    "ember/no-assignment-of-untracked-properties-used-in-tracking-contexts": 1,
    "ember/no-attrs-in-components": 1,
    "ember/no-attrs-snapshot": 1,
    "ember/no-capital-letters-in-routes": 1,
    "ember/no-controller-access-in-routes": [
      1,
      {
        "allowControllerFor": false
      }
    ],
    "ember/no-deeply-nested-dependent-keys-with-each": 1,
    "ember/no-duplicate-dependent-keys": 1,
    "ember/no-ember-super-in-es-classes": 1,
    "ember/no-ember-testing-in-module-scope": 1,
    "ember/no-incorrect-calls-with-inline-anonymous-functions": 1,
    "ember/no-incorrect-computed-macros": 1,
    "ember/no-invalid-debug-function-arguments": 1,
    "ember/no-invalid-dependent-keys": 1,
    "ember/no-noop-setup-on-error-in-before": 1,
    "ember/no-restricted-resolver-tests": 1,
    "ember/no-runloop": 1,
    "ember/no-shadow-route-definition": 1,
    "ember/no-side-effects": [
      1,
      {
        "catchEvents": true,
        "checkPlainGetters": true
      }
    ],
    "ember/no-test-import-export": 1,
    "ember/no-test-support-import": 1,
    "ember/no-tracked-properties-from-args": 1,
    "ember/require-computed-property-dependencies": [
      1,
      {
        "allowDynamicKeys": true,
        "requireServiceNames": false
      }
    ],
    "ember/require-return-from-computed": 1,
    "ember/require-super-in-lifecycle-hooks": [
      1,
      {
        "checkInitOnly": false,
        "checkNativeClasses": true
      }
    ],
    "ember/require-valid-css-selector-in-test-helpers": 1,
    "eslint-plugin/fixer-return": 1,
    "eslint-plugin/no-deprecated-context-methods": 1,
    "eslint-plugin/no-deprecated-report-api": 1,
    "eslint-plugin/no-identical-tests": 1,
    "eslint-plugin/no-missing-message-ids": 1,
    "eslint-plugin/no-missing-placeholders": 1,
    "eslint-plugin/no-only-tests": 1,
    "eslint-plugin/no-unused-message-ids": 1,
    "eslint-plugin/no-unused-placeholders": 1,
    "eslint-plugin/no-useless-token-range": 1,
    "eslint-plugin/prefer-message-ids": 1,
    "eslint-plugin/prefer-object-rule": 1,
    "eslint-plugin/prefer-output-null": 1,
    "eslint-plugin/require-meta-fixable": [
      1,
      {
        "catchNoFixerButFixableProperty": false
      }
    ],
    "eslint-plugin/require-meta-has-suggestions": 1,
    "eslint-plugin/require-meta-schema": [
      1,
      {
        "requireSchemaPropertyWhenOptionless": true
      }
    ],
    "eslint-plugin/require-meta-type": 1,
    "es-x/no-accessor-properties": 1,
    "es-x/no-arbitrary-module-namespace-names": 1,
    "es-x/no-arraybuffer-prototype-transfer": 1,
    "es-x/no-array-from": 1,
    "es-x/no-array-isarray": 1,
    "es-x/no-array-of": 1,
    "es-x/no-array-prototype-at": 1,
    "es-x/no-array-prototype-copywithin": 1,
    "es-x/no-array-prototype-entries": 1,
    "es-x/no-array-prototype-every": 1,
    "es-x/no-array-prototype-fill": 1,
    "es-x/no-array-prototype-filter": 1,
    "es-x/no-array-prototype-find": 1,
    "es-x/no-array-prototype-findindex": 1,
    "es-x/no-array-prototype-findlast-findlastindex": 1,
    "es-x/no-array-prototype-flat": 1,
    "es-x/no-array-prototype-foreach": 1,
    "es-x/no-array-prototype-includes": 1,
    "es-x/no-array-prototype-indexof": 1,
    "es-x/no-array-prototype-keys": 1,
    "es-x/no-array-prototype-lastindexof": 1,
    "es-x/no-array-prototype-map": 1,
    "es-x/no-array-prototype-reduce": 1,
    "es-x/no-array-prototype-reduceright": 1,
    "es-x/no-array-prototype-some": 1,
    "es-x/no-array-prototype-toreversed": 1,
    "es-x/no-array-prototype-tosorted": 1,
    "es-x/no-array-prototype-tospliced": 1,
    "es-x/no-array-prototype-values": 1,
    "es-x/no-array-prototype-with": 1,
    "es-x/no-arrow-functions": 1,
    "es-x/no-async-functions": 1,
    "es-x/no-async-iteration": 1,
    "es-x/no-atomics": 1,
    "es-x/no-atomics-waitasync": 1,
    "es-x/no-bigint": 1,
    "es-x/no-binary-numeric-literals": 1,
    "es-x/no-block-scoped-functions": 1,
    "es-x/no-block-scoped-variables": 1,
    "es-x/no-classes": 1,
    "es-x/no-class-instance-fields": 1,
    "es-x/no-class-private-fields": 1,
    "es-x/no-class-private-methods": 1,
    "es-x/no-class-static-block": 1,
    "es-x/no-class-static-fields": 1,
    "es-x/no-computed-properties": 1,
    "es-x/no-date-now": 1,
    "es-x/no-date-prototype-getyear-setyear": 1,
    "es-x/no-date-prototype-togmtstring": 1,
    "es-x/no-default-parameters": 1,
    "es-x/no-destructuring": 1,
    "es-x/no-dynamic-import": 1,
    "es-x/no-error-cause": 1,
    "es-x/no-escape-unescape": 1,
    "es-x/no-exponential-operators": 1,
    "es-x/no-export-ns-from": 1,
    "es-x/no-for-of-loops": 1,
    "es-x/no-function-declarations-in-if-statement-clauses-without-block": 1,
    "es-x/no-function-prototype-bind": 1,
    "es-x/no-generators": 1,
    "es-x/no-global-this": 1,
    "es-x/no-hashbang": 1,
    "es-x/no-import-meta": 1,
    "es-x/no-initializers-in-for-in": 1,
    "es-x/no-intl-datetimeformat-prototype-formatrange": 1,
    "es-x/no-intl-datetimeformat-prototype-formattoparts": 1,
    "es-x/no-intl-displaynames": 1,
    "es-x/no-intl-getcanonicallocales": 1,
    "es-x/no-intl-listformat": 1,
    "es-x/no-intl-locale": 1,
    "es-x/no-intl-numberformat-prototype-formatrange": 1,
    "es-x/no-intl-numberformat-prototype-formatrangetoparts": 1,
    "es-x/no-intl-numberformat-prototype-formattoparts": 1,
    "es-x/no-intl-pluralrules": 1,
    "es-x/no-intl-pluralrules-prototype-selectrange": 1,
    "es-x/no-intl-relativetimeformat": 1,
    "es-x/no-intl-segmenter": 1,
    "es-x/no-intl-supportedvaluesof": 1,
    "es-x/no-json": 1,
    "es-x/no-json-superset": 1,
    "es-x/no-keyword-properties": 1,
    "es-x/no-labelled-function-declarations": 1,
    "es-x/no-legacy-object-prototype-accessor-methods": 1,
    "es-x/no-logical-assignment-operators": 1,
    "es-x/no-malformed-template-literals": 1,
    "es-x/no-map": 1,
    "es-x/no-map-groupby": 1,
    "es-x/no-math-asinh": 1,
    "es-x/no-math-atanh": 1,
    "es-x/no-math-cbrt": 1,
    "es-x/no-math-clz32": 1,
    "es-x/no-math-cosh": 1,
    "es-x/no-math-expm1": 1,
    "es-x/no-math-fround": 1,
    "es-x/no-math-hypot": 1,
    "es-x/no-math-imul": 1,
    "es-x/no-math-log10": 1,
    "es-x/no-math-log1p": 1,
    "es-x/no-math-log2": 1,
    "es-x/no-math-sign": 1,
    "es-x/no-math-sinh": 1,
    "es-x/no-math-tanh": 1,
    "es-x/no-math-trunc": 1,
    "es-x/no-modules": 1,
    "es-x/no-new-target": 1,
    "es-x/no-nullish-coalescing-operators": 1,
    "es-x/no-number-epsilon": 1,
    "es-x/no-number-isfinite": 1,
    "es-x/no-number-isinteger": 1,
    "es-x/no-number-isnan": 1,
    "es-x/no-number-issafeinteger": 1,
    "es-x/no-number-maxsafeinteger": 1,
    "es-x/no-number-minsafeinteger": 1,
    "es-x/no-number-parsefloat": 1,
    "es-x/no-number-parseint": 1,
    "es-x/no-numeric-separators": 1,
    "es-x/no-object-assign": 1,
    "es-x/no-object-create": 1,
    "es-x/no-object-defineproperties": 1,
    "es-x/no-object-defineproperty": 1,
    "es-x/no-object-entries": 1,
    "es-x/no-object-freeze": 1,
    "es-x/no-object-fromentries": 1,
    "es-x/no-object-getownpropertydescriptor": 1,
    "es-x/no-object-getownpropertydescriptors": 1,
    "es-x/no-object-getownpropertynames": 1,
    "es-x/no-object-getownpropertysymbols": 1,
    "es-x/no-object-getprototypeof": 1,
    "es-x/no-object-groupby": 1,
    "es-x/no-object-hasown": 1,
    "es-x/no-object-is": 1,
    "es-x/no-object-isextensible": 1,
    "es-x/no-object-isfrozen": 1,
    "es-x/no-object-issealed": 1,
    "es-x/no-object-keys": 1,
    "es-x/no-object-preventextensions": 1,
    "es-x/no-object-seal": 1,
    "es-x/no-object-setprototypeof": 1,
    "es-x/no-object-super-properties": 1,
    "es-x/no-object-values": 1,
    "es-x/no-octal-numeric-literals": 1,
    "es-x/no-optional-catch-binding": 1,
    "es-x/no-optional-chaining": 1,
    "es-x/no-private-in": 1,
    "es-x/no-promise": 1,
    "es-x/no-promise-all-settled": 1,
    "es-x/no-promise-any": 1,
    "es-x/no-promise-prototype-finally": 1,
    "es-x/no-promise-withresolvers": 1,
    "es-x/no-property-shorthands": 1,
    "es-x/no-proxy": 1,
    "es-x/no-reflect": 1,
    "es-x/no-regexp-d-flag": 1,
    "es-x/no-regexp-duplicate-named-capturing-groups": 1,
    "es-x/no-regexp-lookbehind-assertions": 1,
    "es-x/no-regexp-named-capture-groups": 1,
    "es-x/no-regexp-prototype-compile": 1,
    "es-x/no-regexp-prototype-flags": 1,
    "es-x/no-regexp-s-flag": 1,
    "es-x/no-regexp-u-flag": 1,
    "es-x/no-regexp-unicode-property-escapes": 1,
    "es-x/no-regexp-unicode-property-escapes-2019": 1,
    "es-x/no-regexp-unicode-property-escapes-2020": 1,
    "es-x/no-regexp-unicode-property-escapes-2021": 1,
    "es-x/no-regexp-unicode-property-escapes-2022": 1,
    "es-x/no-regexp-unicode-property-escapes-2023": 1,
    "es-x/no-regexp-v-flag": 1,
    "es-x/no-regexp-y-flag": 1,
    "es-x/no-resizable-and-growable-arraybuffers": 1,
    "es-x/no-rest-parameters": 1,
    "es-x/no-rest-spread-properties": 1,
    "es-x/no-set": 1,
    "es-x/no-set-prototype-difference": 1,
    "es-x/no-set-prototype-intersection": 1,
    "es-x/no-set-prototype-isdisjointfrom": 1,
    "es-x/no-set-prototype-issubsetof": 1,
    "es-x/no-set-prototype-issupersetof": 1,
    "es-x/no-set-prototype-symmetricdifference": 1,
    "es-x/no-set-prototype-union": 1,
    "es-x/no-shadow-catch-param": 1,
    "es-x/no-shared-array-buffer": 1,
    "es-x/no-spread-elements": 1,
    "es-x/no-string-create-html-methods": 1,
    "es-x/no-string-fromcodepoint": 1,
    "es-x/no-string-prototype-at": 1,
    "es-x/no-string-prototype-codepointat": 1,
    "es-x/no-string-prototype-includes": 1,
    "es-x/no-string-prototype-iswellformed": 1,
    "es-x/no-string-prototype-matchall": 1,
    "es-x/no-string-prototype-normalize": 1,
    "es-x/no-string-prototype-padstart-padend": 1,
    "es-x/no-string-prototype-repeat": 1,
    "es-x/no-string-prototype-replaceall": 1,
    "es-x/no-string-prototype-startswith": 1,
    "es-x/no-string-prototype-substr": 1,
    "es-x/no-string-prototype-towellformed": 1,
    "es-x/no-string-prototype-trim": 1,
    "es-x/no-string-prototype-trimleft-trimright": 1,
    "es-x/no-string-prototype-trimstart-trimend": 1,
    "es-x/no-string-raw": 1,
    "es-x/no-subclassing-builtins": 1,
    "es-x/no-symbol": 1,
    "es-x/no-symbol-prototype-description": 1,
    "es-x/no-template-literals": 1,
    "es-x/no-top-level-await": 1,
    "es-x/no-trailing-commas": 1,
    "es-x/no-trailing-function-commas": 1,
    "es-x/no-typed-arrays": 1,
    "es-x/no-unicode-codepoint-escapes": 1,
    "es-x/no-weak-map": 1,
    "es-x/no-weakrefs": 1,
    "es-x/no-weak-set": 1,
    "for-direction": 1,
    "getter-return": 1,
    "import/default": 1,
    "import/export": 1,
    "import/named": 1,
    "import/namespace": [
      1,
      {
        "allowComputed": false
      }
    ],
    "import/no-duplicates": 1,
    "import/no-extraneous-dependencies": 1,
    "import/no-import-module-exports": 1,
    "import/no-named-as-default": 1,
    "import/no-self-import": 1,
    "import/no-unresolved": [
      1,
      {
        "caseSensitive": true,
        "caseSensitiveStrict": false
      }
    ],
    "import/no-webpack-loader-syntax": 1,
    "jest/no-conditional-expect": 1,
    "jest/no-conditional-in-test": 1,
    "jest/no-confusing-set-timeout": 1,
    "jest/no-interpolation-in-snapshots": 1,
    "jest/no-mocks-import": 1,
    "jest/prefer-importing-jest-globals": 1,
    "jest/valid-describe-callback": 1,
    "jsonc/no-bigint-literals": 1,
    "jsonc/no-binary-expression": 1,
    "jsonc/no-binary-numeric-literals": 1,
    "jsonc/no-comments": 1,
    "jsonc/no-dupe-keys": 1,
    "jsonc/no-escape-sequence-in-identifier": 1,
    "jsonc/no-hexadecimal-numeric-literals": 1,
    "jsonc/no-infinity": 1,
    "jsonc/no-irregular-whitespace": 1,
    "jsonc/no-nan": 1,
    "jsonc/no-number-props": 1,
    "jsonc/no-numeric-separators": 1,
    "jsonc/no-octal-numeric-literals": 1,
    "jsonc/no-parenthesized": 1,
    "jsonc/no-plus-sign": 1,
    "jsonc/no-regexp-literals": 1,
    "jsonc/no-sparse-arrays": 1,
    "jsonc/no-template-literals": 1,
    "jsonc/no-undefined-value": 1,
    "jsonc/no-unicode-codepoint-escapes": 1,
    "jsonc/valid-json-number": 1,
    "jsonc/vue-custom-block_no-parsing-error": 1,
    "lodash/callback-binding": 1,
    "lodash/chaining": 1,
    "lodash/chain-style": 1,
    "lodash/collection-method-value": 1,
    "lodash/collection-ordering": 1,
    "lodash/collection-return": 1,
    "lodash/consistent-compose": 1,
    "lodash/identity-shorthand": 1,
    "lodash/import-scope": 1,
    "lodash/matches-prop-shorthand": 1,
    "lodash/matches-shorthand": 1,
    "lodash/no-commit": 1,
    "lodash/no-double-unwrap": 1,
    "lodash/no-extra-args": 1,
    "lodash/no-unbound-this": 1,
    "lodash/path-style": 1,
    "lodash/prefer-compact": 1,
    "lodash/prefer-constant": 1,
    "lodash/prefer-filter": 1,
    "lodash/prefer-find": 1,
    "lodash/prefer-flat-map": 1,
    "lodash/prefer-get": 1,
    "lodash/prefer-immutable-method": 1,
    "lodash/prefer-includes": 1,
    "lodash/prefer-invoke-map": 1,
    "lodash/prefer-is-nil": 1,
    "lodash/prefer-lodash-chain": 1,
    "lodash/prefer-lodash-method": 1,
    "lodash/prefer-lodash-typecheck": 1,
    "lodash/prefer-map": 1,
    "lodash/prefer-matches": 1,
    "lodash/prefer-noop": 1,
    "lodash/prefer-over-quantifier": 1,
    "lodash/preferred-alias": 1,
    "lodash/prefer-reject": 1,
    "lodash/prefer-some": 1,
    "lodash/prefer-startswith": 1,
    "lodash/prefer-thru": 1,
    "lodash/prefer-times": 1,
    "lodash/prefer-wrapper-method": 1,
    "lodash/prop-shorthand": 1,
    "lodash/unwrap": 1,
    "@lwc/lwc_no-attributes-during-construction": 1,
    "@lwc/lwc_no-unsupported-ssr-properties": 1,
    "mocha/handle-done-callback": [
      1,
      {
        "ignoreSkipped": false
      }
    ],
    "mocha/no-async-describe": 1,
    "mocha/no-exclusive-tests": 1,
    "mocha/no-nested-tests": 1,
    "mocha/no-return-and-callback": 1,
    "mocha/no-skipped-tests": 1,
    "mocha/no-top-level-hooks": 1,
    "n/hashbang": 1,
    "n/no-callback-literal": 1,
    "n/no-deprecated-api": 1,
    "n/no-exports-assign": 1,
    "n/no-extraneous-import": 1,
    "n/no-extraneous-require": 1,
    "n/no-missing-import": [
      1,
      {
        "ignoreTypeImport": false
      }
    ],
    "n/no-missing-require": 1,
    "n/no-unpublished-bin": 1,
    "n/no-unpublished-import": [
      1,
      {
        "ignoreTypeImport": false,
        "ignorePrivate": true
      }
    ],
    "n/no-unpublished-require": [
      1,
      {
        "ignorePrivate": true
      }
    ],
    "n/no-unsupported-features_es-builtins": 1,
    "n/no-unsupported-features_es-syntax": 1,
    "n/no-unsupported-features_node-builtins": 1,
    "no-async-promise-executor": 1,
    "no-await-in-loop": 1,
    "no-buffer-constructor": 1,
    "no-case-declarations": 1,
    "no-class-assign": 1,
    "no-compare-neg-zero": 1,
    "no-cond-assign": [
      1,
      {
        "unnamedParam": "except-parens"
      }
    ],
    "no-constant-binary-expression": 1,
    "no-constant-condition": 1,
    "no-const-assign": 1,
    "no-constructor-return": 1,
    "no-control-regex": 1,
    "no-debugger": 1,
    "no-delete-var": 1,
    "no-dupe-args": 1,
    "no-dupe-class-members": 1,
    "no-dupe-else-if": 1,
    "no-dupe-keys": 1,
    "no-duplicate-case": 1,
    "no-duplicate-imports": 1,
    "no-empty": 1,
    "no-empty-character-class": 1,
    "no-empty-pattern": 1,
    "no-empty-static-block": 1,
    "no-ex-assign": 1,
    "no-extra-boolean-cast": 1,
    "no-fallthrough": 1,
    "no-func-assign": 1,
    "no-global-assign": 1,
    "no-import-assign": 1,
    "no-inner-declarations": [
      1,
      {
        "unnamedParam": "functions"
      }
    ],
    "no-invalid-regexp": 1,
    "no-irregular-whitespace": 1,
    "no-loss-of-precision": 1,
    "no-negated-in-lhs": 1,
    "no-new-native-nonconstructor": 1,
    "no-new-symbol": 1,
    "no-nonoctal-decimal-escape": 1,
    "no-obj-calls": 1,
    "no-octal": 1,
    "no-promise-executor-return": 1,
    "no-prototype-builtins": 1,
    "no-redeclare": 1,
    "no-regex-spaces": 1,
    "no-self-assign": 1,
    "no-self-compare": 1,
    "no-setter-return": 1,
    "no-shadow-restricted-names": 1,
    "no-sparse-arrays": 1,
    "no-template-curly-in-string": 1,
    "no-this-before-super": 1,
    "no-undef": 1,
    "no-unexpected-multiline": 1,
    "no-unmodified-loop-condition": 1,
    "no-unreachable": 1,
    "no-unreachable-loop": 1,
    "no-unsafe-finally": 1,
    "no-unsafe-negation": 1,
    "no-unsafe-optional-chaining": 1,
    "no-unused-labels": 1,
    "no-unused-private-class-members": 1,
    "no-unused-vars": 1,
    "no-use-before-define": 1,
    "no-useless-assignment": 1,
    "no-useless-backreference": 1,
    "no-useless-catch": 1,
    "no-useless-escape": 1,
    "no-with": 1,
    "n/process-exit-as-throw": 1,
    "playwright/expect-expect": 1,
    "playwright/missing-playwright-await": 1,
    "playwright/no-commented-out-tests": 1,
    "playwright/no-conditional-expect": 1,
    "playwright/no-conditional-in-test": 1,
    "playwright/no-eval": 1,
    "playwright/no-focused-test": 1,
    "playwright/no-nested-step": 1,
    "playwright/no-networkidle": 1,
    "playwright/no-nth-methods": 1,
    "playwright/no-page-pause": 1,
    "playwright/no-unsafe-references": 1,
    "playwright/no-useless-await": 1,
    "playwright/no-useless-not": 1,
    "playwright/valid-describe-callback": 1,
    "playwright/valid-expect": 1,
    "promise/always-return": 1,
    "promise/catch-or-return": 1,
    "promise/no-multiple-resolved": 1,
    "promise/no-new-statics": 1,
    "promise/no-return-in-finally": 1,
    "promise/spec-only": 1,
    "promise/valid-params": 1,
    "react/button-has-type": [
      1,
      {
        "button": true,
        "submit": true,
        "reset": true
      }
    ],
    "react-hooks/rules-of-hooks": 1,
    "react/jsx-key": [
      1,
      {
        "checkFragmentShorthand": false,
        "checkKeyMustBeforeSpread": false,
        "warnOnDuplicates": false
      }
    ],
    "react/jsx-no-comment-textnodes": 1,
    "react/jsx-no-duplicate-props": 1,
    "react/jsx-no-leaked-render": [
      1,
      {
        "validStrategies": [
          "ternary",
          "coerce"
        ]
      }
    ],
    "react/jsx-no-undef": 1,
    "react/no-access-state-in-setstate": 1,
    "react/no-danger-with-children": 1,
    "react/no-direct-mutation-state": 1,
    "react/no-namespace": 1,
    "react/no-redundant-should-component-update": 1,
    "react/no-this-in-sfc": 1,
    "react/no-unescaped-entities": 1,
    "react/no-unknown-property": [
      1,
      {
        "requireDataLowercase": false
      }
    ],
    "react/no-unstable-nested-components": 1,
    "react/prefer-exact-props": 1,
    "react/react-in-jsx-scope": 1,
    "react/require-render-return": 1,
    "react/style-prop-object": 1,
    "redux-saga/no-unhandled-errors": 1,
    "redux-saga/no-yield-in-race": 1,
    "redux-saga/yield-effects": 1,
    "regexp/confusing-quantifier": 1,
    "regexp/no-contradiction-with-assertion": 1,
    "regexp/no-empty-alternative": 1,
    "regexp/no-invalid-regexp": 1,
    "regexp/no-lazy-ends": 1,
    "regexp/no-misleading-capturing-group": 1,
    "regexp/no-misleading-unicode-character": 1,
    "regexp/no-missing-g-flag": 1,
    "regexp/no-optional-assertion": 1,
    "regexp/no-potentially-useless-backreference": 1,
    "regexp/no-super-linear-backtracking": 1,
    "regexp/no-super-linear-move": 1,
    "regexp/no-useless-assertions": 1,
    "regexp/optimal-lookaround-quantifier": 1,
    "require-atomic-updates": 1,
    "require-yield": 1,
    "security/detect-bidi-characters": 1,
    "security/detect-buffer-noassert": 1,
    "security/detect-child-process": 1,
    "security/detect-disable-mustache-escape": 1,
    "security/detect-eval-with-expression": 1,
    "security/detect-new-buffer": 1,
    "security/detect-no-csrf-before-method-override": 1,
    "security/detect-non-literal-fs-filename": 1,
    "security/detect-non-literal-regexp": 1,
    "security/detect-non-literal-require": 1,
    "security/detect-object-injection": 1,
    "security/detect-possible-timing-attacks": 1,
    "security/detect-pseudoRandomBytes": 1,
    "security/detect-unsafe-regex": 1,
    "security-node/detect-absence-of-name-option-in-exrpress-session": 1,
    "security-node/detect-child-process": 1,
    "security-node/detect-dangerous-redirects": 1,
    "security-node/detect-eval-with-expr": 1,
    "security-node/detect-html-injection": 1,
    "security-node/detect-improper-exception-handling": 1,
    "security-node/detect-non-literal-require-calls": 1,
    "security-node/detect-nosql-injection": 1,
    "security-node/detect-option-multiplestatements-in-mysql": 1,
    "security-node/detect-option-rejectunauthorized-in-nodejs-httpsrequest": 1,
    "security-node/detect-option-unsafe-in-serialize-javascript-npm-package": 1,
    "security-node/detect-possible-timing-attacks": 1,
    "security-node/detect-security-missconfiguration-cookie": 1,
    "security-node/detect-unhandled-async-errors": 1,
    "security-node/detect-unhandled-event-errors": 1,
    "security-node/disable-ssl-across-node-server": 1,
    "security-node/non-literal-reg-expr": 1,
    "@shopify/react-initialize-state": 1,
    "@shopify/react-type-state": 1,
    "sonarjs/anchor-precedence": 1,
    "sonarjs/array-callback-without-return": 1,
    "sonarjs/aws-apigateway-public-api": 1,
    "sonarjs/aws-ec2-rds-dms-public": 1,
    "sonarjs/aws-ec2-unencrypted-ebs-volume": 1,
    "sonarjs/aws-efs-unencrypted": 1,
    "sonarjs/aws-iam-all-privileges": 1,
    "sonarjs/aws-iam-all-resources-accessible": 1,
    "sonarjs/aws-iam-privilege-escalation": 1,
    "sonarjs/aws-iam-public-access": 1,
    "sonarjs/aws-opensearchservice-domain": 1,
    "sonarjs/aws-rds-unencrypted-databases": 1,
    "sonarjs/aws-restricted-ip-admin-access": 1,
    "sonarjs/aws-s3-bucket-granted-access": 1,
    "sonarjs/aws-s3-bucket-insecure-http": 1,
    "sonarjs/aws-s3-bucket-public-access": 1,
    "sonarjs/aws-s3-bucket-versioning": 1,
    "sonarjs/aws-sagemaker-unencrypted-notebook": 1,
    "sonarjs/aws-sns-unencrypted-topics": 1,
    "sonarjs/aws-sqs-unencrypted-queue": 1,
    "sonarjs/bitwise-operators": 1,
    "sonarjs/code-eval": 1,
    "sonarjs/comma-or-logical-or-case": 1,
    "sonarjs/confidential-information-logging": 1,
    "sonarjs/constructor-for-side-effects": 1,
    "sonarjs/content-length": 1,
    "sonarjs/content-security-policy": 1,
    "sonarjs/cookie-no-httponly": 1,
    "sonarjs/cors": 1,
    "sonarjs/csrf": 1,
    "sonarjs/different-types-comparison": 1,
    "sonarjs/disabled-auto-escaping": 1,
    "sonarjs/disabled-resource-integrity": 1,
    "sonarjs/disabled-timeout": 1,
    "sonarjs/empty-string-repetition": 1,
    "sonarjs/encryption-secure-mode": 1,
    "sonarjs/existing-groups": 1,
    "sonarjs/file-permissions": 1,
    "sonarjs/file-uploads": 1,
    "sonarjs/for-in": 1,
    "sonarjs/for-loop-increment-sign": 1,
    "sonarjs/frame-ancestors": 1,
    "sonarjs/generator-without-yield": 1,
    "sonarjs/hashing": 1,
    "sonarjs/hidden-files": 1,
    "sonarjs/in-operator-type-error": 1,
    "sonarjs/insecure-cookie": 1,
    "sonarjs/insecure-jwt-token": 1,
    "sonarjs/jsx-no-leaked-render": 1,
    "sonarjs/link-with-target-blank": 1,
    "sonarjs/new-operator-misuse": 1,
    "sonarjs/no-all-duplicated-branches": 1,
    "sonarjs/no-alphabetical-sort": 1,
    "sonarjs/no-angular-bypass-sanitization": 1,
    "sonarjs/no-built-in-override": 1,
    "sonarjs/no-clear-text-protocols": 1,
    "sonarjs/no-collection-size-mischeck": 1,
    "sonarjs/no-control-regex": 1,
    "sonarjs/no-delete-var": 1,
    "sonarjs/no-element-overwrite": 1,
    "sonarjs/no-empty-alternatives": 1,
    "sonarjs/no-empty-character-class": 1,
    "sonarjs/no-empty-collection": 1,
    "sonarjs/no-exclusive-tests": 1,
    "sonarjs/no-extra-arguments": 1,
    "sonarjs/no-function-declaration-in-block": 1,
    "sonarjs/no-globals-shadowing": 1,
    "sonarjs/no-hardcoded-ip": 1,
    "sonarjs/no-hardcoded-passwords": 1,
    "sonarjs/no-hardcoded-secrets": 1,
    "sonarjs/no-hook-setter-in-body": 1,
    "sonarjs/no-identical-conditions": 1,
    "sonarjs/no-identical-expressions": 1,
    "sonarjs/no-ignored-return": 1,
    "sonarjs/no-intrusive-permissions": 1,
    "sonarjs/no-invalid-regexp": 1,
    "sonarjs/no-ip-forward": 1,
    "sonarjs/no-literal-call": 1,
    "sonarjs/no-mime-sniff": 1,
    "sonarjs/no-misleading-character-class": 1,
    "sonarjs/no-mixed-content": 1,
    "sonarjs/non-existent-operator": 1,
    "sonarjs/no-one-iteration-loop": 1,
    "sonarjs/no-os-command-from-path": 1,
    "sonarjs/no-parameter-reassignment": 1,
    "sonarjs/no-reference-error": 1,
    "sonarjs/no-referrer-policy": 1,
    "sonarjs/no-same-argument-assert": 1,
    "sonarjs/no-try-promise": 1,
    "sonarjs/no-unsafe-unzip": 1,
    "sonarjs/no-unthrown-error": 1,
    "sonarjs/no-useless-increment": 1,
    "sonarjs/no-useless-intersection": 1,
    "sonarjs/no-useless-react-setstate": 1,
    "sonarjs/no-use-of-empty-return-value": 1,
    "sonarjs/no-weak-cipher": 1,
    "sonarjs/no-weak-keys": 1,
    "sonarjs/null-dereference": 1,
    "sonarjs/os-command": 1,
    "sonarjs/post-message": 1,
    "sonarjs/production-debug": 1,
    "sonarjs/pseudo-random": 1,
    "sonarjs/publicly-writable-directories": 1,
    "sonarjs/reduce-initial-value": 1,
    "sonarjs/session-regeneration": 1,
    "sonarjs/slow-regex": 1,
    "sonarjs/sql-queries": 1,
    "sonarjs/stateful-regex": 1,
    "sonarjs/strict-transport-security": 1,
    "sonarjs/super-invocation": 1,
    "sonarjs/table-header": 1,
    "sonarjs/table-header-reference": 1,
    "sonarjs/unicode-aware-regex": 1,
    "sonarjs/unverified-certificate": 1,
    "sonarjs/unverified-hostname": 1,
    "sonarjs/updated-const-var": 1,
    "sonarjs/weak-ssl": 1,
    "sonarjs/xml-parser-xxe": 1,
    "sonarjs/x-powered-by": 1,
    "storybook/await-interactions": 1,
    "storybook/context-in-play-function": 1,
    "storybook/default-exports": 1,
    "storybook/hierarchy-separator": 1,
    "storybook/meta-inline-properties": 1,
    "storybook/no-stories-of": 1,
    "storybook/no-title-property-in-meta": 1,
    "storybook/no-uninstalled-addons": 1,
    "storybook/story-exports": 1,
    "suitescript/api-version": 1,
    "suitescript/entry-points": 1,
    "suitescript/no-extra-modules": 1,
    "suitescript/no-invalid-modules": 1,
    "suitescript/no-module-extensions": 1,
    "suitescript/script-type": 1,
    "svelte/comment-directive": 1,
    "svelte/no-at-debug-tags": 1,
    "svelte/no-dom-manipulating": 1,
    "svelte/no-dupe-else-if-blocks": 1,
    "svelte/no-dupe-on-directives": 1,
    "svelte/no-dupe-style-properties": 1,
    "svelte/no-dupe-use-directives": 1,
    "svelte/no-export-load-in-svelte-module-in-kit-pages": 1,
    "svelte/no-ignored-unsubscribe": 1,
    "svelte/no-inner-declarations": 1,
    "svelte/no-not-function-handler": 1,
    "svelte/no-object-in-text-mustaches": 1,
    "svelte/no-raw-special-elements": 1,
    "svelte/no-reactive-reassign": 1,
    "svelte/no-shorthand-style-property-overrides": 1,
    "svelte/no-store-async": 1,
    "svelte/no-svelte-internal": 1,
    "svelte/no-target-blank": 1,
    "svelte/no-unknown-style-directive-property": 1,
    "svelte/require-store-reactive-access": 1,
    "svelte/system": 1,
    "svelte/valid-compile": 1,
    "svelte/valid-prop-names-in-kit-pages": 1,
    "svelte/valid-style-parse": 1,
    "tailwindcss/migration-from-tailwind-2": 1,
    "tailwindcss/no-contradicting-classname": 1,
    "@tanstack/query_exhaustive-deps": 1,
    "@tanstack/query_infinite-query-property-order": 1,
    "@tanstack/query_no-rest-destructuring": 1,
    "@tanstack/query_no-unstable-deps": 1,
    "@tanstack/query_stable-query-client": 1,
    "testing-library/await-async-events": [
      1,
      {
        "eventModule": "userEvent"
      }
    ],
    "testing-library/await-async-queries": 1,
    "testing-library/await-async-utils": 1,
    "testing-library/no-await-sync-events": [
      1,
      {
        "eventModules": [
          "fire-event"
        ]
      }
    ],
    "testing-library/no-await-sync-queries": 1,
    "testing-library/no-container": 1,
    "testing-library/no-debugging-utils": 1,
    "testing-library/no-dom-import": 1,
    "testing-library/no-manual-cleanup": 1,
    "testing-library/no-node-access": 1,
    "testing-library/no-promise-in-fire-event": 1,
    "testing-library/no-render-in-lifecycle": 1,
    "testing-library/no-unnecessary-act": 1,
    "testing-library/no-wait-for-snapshot": 1,
    "testing-library/prefer-query-by-disappearance": 1,
    "test-selectors/anchor": 1,
    "test-selectors/button": 1,
    "test-selectors/input": 1,
    "test-selectors/onChange": 1,
    "test-selectors/onClick": 1,
    "test-selectors/onKeyDown": 1,
    "test-selectors/onKeyUp": 1,
    "test-selectors/onSubmit": 1,
    "@typescript-eslint/adjacent-overload-signatures": 1,
    "@typescript-eslint/array-type": 1,
    "@typescript-eslint/await-thenable": 1,
    "@typescript-eslint/ban-ts-comment": [
      1,
      {
        "minimumDescriptionLength": 3
      }
    ],
    "@typescript-eslint/ban-tslint-comment": 1,
    "@typescript-eslint/class-literal-property-style": 1,
    "@typescript-eslint/consistent-generic-constructors": 1,
    "@typescript-eslint/consistent-indexed-object-style": 1,
    "@typescript-eslint/consistent-type-assertions": 1,
    "@typescript-eslint/consistent-type-definitions": 1,
    "@typescript-eslint/dot-notation": [
      1,
      {
        "allowKeywords": true,
        "allowPattern": "",
        "allowProtectedClassPropertyAccess": false,
        "allowPrivateClassPropertyAccess": false,
        "allowIndexSignaturePropertyAccess": false
      }
    ],
    "@typescript-eslint/explicit-function-return-type": 1,
    "@typescript-eslint/explicit-member-accessibility": 1,
    "@typescript-eslint/explicit-module-boundary-types": 1,
    "@typescript-eslint/no-array-constructor": 1,
    "@typescript-eslint/no-array-delete": 1,
    "@typescript-eslint/no-base-to-string": 1,
    "@typescript-eslint/no-confusing-non-null-assertion": 1,
    "@typescript-eslint/no-confusing-void-expression": 1,
    "@typescript-eslint/no-deprecated": 1,
    "@typescript-eslint/no-dupe-class-members": 1,
    "@typescript-eslint/no-duplicate-enum-values": 1,
    "@typescript-eslint/no-duplicate-type-constituents": 1,
    "@typescript-eslint/no-dynamic-delete": 1,
    "@typescript-eslint/no-empty-function": 1,
    "@typescript-eslint/no-empty-object-type": 1,
    "@typescript-eslint/no-explicit-any": 1,
    "@typescript-eslint/no-extraneous-class": 1,
    "@typescript-eslint/no-extra-non-null-assertion": 1,
    "@typescript-eslint/no-floating-promises": 1,
    "@typescript-eslint/no-for-in-array": 1,
    "@typescript-eslint/no-implied-eval": 1,
    "@typescript-eslint/no-import-type-side-effects": 1,
    "@typescript-eslint/no-inferrable-types": 1,
    "@typescript-eslint/no-invalid-void-type": 1,
    "@typescript-eslint/no-loss-of-precision": 1,
    "@typescript-eslint/no-meaningless-void-operator": [
      1,
      {
        "checkNever": false
      }
    ],
    "@typescript-eslint/no-misused-new": 1,
    "@typescript-eslint/no-misused-promises": 1,
    "@typescript-eslint/no-misused-spread": 1,
    "@typescript-eslint/no-mixed-enums": 1,
    "@typescript-eslint/no-namespace": 1,
    "@typescript-eslint/non-nullable-type-assertion-style": 1,
    "@typescript-eslint/no-non-null-asserted-nullish-coalescing": 1,
    "@typescript-eslint/no-non-null-asserted-optional-chain": 1,
    "@typescript-eslint/no-non-null-assertion": 1,
    "@typescript-eslint/no-redundant-type-constituents": 1,
    "@typescript-eslint/no-require-imports": 1,
    "@typescript-eslint/no-this-alias": 1,
    "@typescript-eslint/no-unnecessary-boolean-literal-compare": 1,
    "@typescript-eslint/no-unnecessary-condition": 1,
    "@typescript-eslint/no-unnecessary-template-expression": 1,
    "@typescript-eslint/no-unnecessary-type-arguments": 1,
    "@typescript-eslint/no-unnecessary-type-assertion": 1,
    "@typescript-eslint/no-unnecessary-type-constraint": 1,
    "@typescript-eslint/no-unnecessary-type-parameters": 1,
    "@typescript-eslint/no-unused-expressions": 1,
    "@typescript-eslint/no-unused-vars": 1,
    "@typescript-eslint/no-use-before-define": 1,
    "@typescript-eslint/no-useless-constructor": 1,
    "@typescript-eslint/no-var-requires": 1,
    "@typescript-eslint/no-wrapper-object-types": 1,
    "@typescript-eslint/only-throw-error": 1,
    "@typescript-eslint/parameter-properties": 1,
    "@typescript-eslint/prefer-as-const": 1,
    "@typescript-eslint/prefer-find": 1,
    "@typescript-eslint/prefer-for-of": 1,
    "@typescript-eslint/prefer-function-type": 1,
    "@typescript-eslint/prefer-includes": 1,
    "@typescript-eslint/prefer-literal-enum-member": 1,
    "@typescript-eslint/prefer-namespace-keyword": 1,
    "@typescript-eslint/prefer-nullish-coalescing": 1,
    "@typescript-eslint/prefer-optional-chain": 1,
    "@typescript-eslint/prefer-promise-reject-errors": 1,
    "@typescript-eslint/prefer-reduce-type-parameter": 1,
    "@typescript-eslint/prefer-regexp-exec": 1,
    "@typescript-eslint/prefer-return-this-type": 1,
    "@typescript-eslint/prefer-string-starts-ends-with": 1,
    "@typescript-eslint/prefer-ts-expect-error": 1,
    "@typescript-eslint/related-getter-setter-pairs": 1,
    "@typescript-eslint/require-array-sort-compare": 1,
    "@typescript-eslint/require-await": 1,
    "@typescript-eslint/restrict-plus-operands": 1,
    "@typescript-eslint/restrict-template-expressions": 1,
    "@typescript-eslint/return-await": 1,
    "@typescript-eslint/triple-slash-reference": 1,
    "@typescript-eslint/unbound-method": 1,
    "@typescript-eslint/unified-signatures": 1,
    "@typescript-eslint/use-unknown-in-catch-callback-variable": 1,
    "unicorn/consistent-assert": 1,
    "unicorn/consistent-existence-index-check": 1,
    "unicorn/custom-error-definition": 1,
    "unicorn/error-message": 1,
    "unicorn/explicit-length-check": [
      1,
      {
        "non-zero": "greater-than"
      }
    ],
    "unicorn/import-style": 1,
    "unicorn/no-accessor-recursion": 1,
    "unicorn/no-array-callback-reference": 1,
    "unicorn/no-document-cookie": 1,
    "unicorn/no-instanceof-builtins": 1,
    "unicorn/no-invalid-fetch-options": 1,
    "unicorn/no-invalid-remove-event-listener": 1,
    "unicorn/no-negation-in-equality-check": 1,
    "unicorn/no-new-buffer": 1,
    "unicorn/no-object-as-default-parameter": 1,
    "unicorn/no-thenable": 1,
    "unicorn/prefer-math-min-max": 1,
    "unicorn/require-post-message-target-origin": 1,
    "unused-imports/no-unused-imports": 1,
    "unused-imports/no-unused-vars": 1,
    "use-isnan": 1,
    "valid-typeof": 1,
    "@vitest/consistent-test-filename": [
      1,
      {
        "pattern": ".*\\.test\\.[tj]sx?$",
        "allTestPattern": ".*\\.(test|spec)\\.[tj]sx?$"
      }
    ],
    "@vitest/max-nested-describe": 1,
    "@vitest/no-conditional-expect": 1,
    "@vitest/no-conditional-in-test": 1,
    "@vitest/no-conditional-tests": 1,
    "@vitest/no-focused-tests": [
      1,
      {
        "fixable": true
      }
    ],
    "@vitest/no-identical-title": 1,
    "@vitest/no-interpolation-in-snapshots": 1,
    "@vitest/no-mocks-import": 1,
    "@vitest/no-test-return-statement": 1,
    "@vitest/prefer-lowercase-title": [
      1,
      {
        "ignoreTopLevelDescribe": false,
        "lowercaseFirstCharacterOnly": true
      }
    ],
    "@vitest/require-local-test-context-for-concurrent-snapshots": 1,
    "@vitest/valid-describe-callback": 1,
    "vue/comment-directive": 1,
    "vuejs-accessibility/alt-text": 1,
    "vuejs-accessibility/anchor-has-content": 1,
    "vuejs-accessibility/aria-props": 1,
    "vuejs-accessibility/aria-role": [
      1,
      {
        "ignoreNonDOM": true
      }
    ],
    "vuejs-accessibility/aria-unsupported-elements": 1,
    "vuejs-accessibility/click-events-have-key-events": 1,
    "vuejs-accessibility/form-control-has-label": 1,
    "vuejs-accessibility/heading-has-content": 1,
    "vuejs-accessibility/iframe-has-title": 1,
    "vuejs-accessibility/interactive-supports-focus": 1,
    "vuejs-accessibility/label-has-for": 1,
    "vuejs-accessibility/media-has-caption": 1,
    "vuejs-accessibility/mouse-events-have-key-events": 1,
    "vuejs-accessibility/no-access-key": 1,
    "vuejs-accessibility/no-aria-hidden-on-focusable": 1,
    "vuejs-accessibility/no-autofocus": [
      1,
      {
        "ignoreNonDOM": true
      }
    ],
    "vuejs-accessibility/no-distracting-elements": 1,
    "vuejs-accessibility/no-redundant-roles": 1,
    "vuejs-accessibility/no-role-presentation-on-focusable": 1,
    "vuejs-accessibility/no-static-element-interactions": 1,
    "vuejs-accessibility/role-has-required-aria-props": 1,
    "vuejs-accessibility/tabindex-no-positive": 1,
    "vue/jsx-uses-vars": 1,
    "vue/match-component-import-name": 1,
    "vue/max-lines-per-block": 1,
    "vue/max-props": 1,
    "vue/max-template-depth": 1,
    "vue/no-arrow-functions-in-watch": 1,
    "vue/no-async-in-computed-properties": 1,
    "vue/no-child-content": 1,
    "vue/no-computed-properties-in-data": 1,
    "vue/no-constant-condition": 1,
    "vue/no-custom-modifiers-on-v-model": 1,
    "vue/no-deprecated-data-object-declaration": 1,
    "vue/no-deprecated-delete-set": 1,
    "vue/no-deprecated-destroyed-lifecycle": 1,
    "vue/no-deprecated-dollar-listeners-api": 1,
    "vue/no-deprecated-dollar-scopedslots-api": 1,
    "vue/no-deprecated-events-api": 1,
    "vue/no-deprecated-filter": 1,
    "vue/no-deprecated-functional-template": 1,
    "vue/no-deprecated-html-element-is": 1,
    "vue/no-deprecated-inline-template": 1,
    "vue/no-deprecated-model-definition": 1,
    "vue/no-deprecated-props-default-this": 1,
    "vue/no-deprecated-router-link-tag-prop": 1,
    "vue/no-deprecated-v-bind-sync": 1,
    "vue/no-deprecated-v-on-native-modifier": 1,
    "vue/no-deprecated-v-on-number-modifiers": 1,
    "vue/no-deprecated-vue-config-keycodes": 1,
    "vue/no-dupe-keys": 1,
    "vue/no-dupe-v-else-if": 1,
    "vue/no-duplicate-attributes": 1,
    "vue/no-empty-pattern": 1,
    "vue/no-export-in-script-setup": 1,
    "vue/no-expose-after-await": 1,
    "vue/no-irregular-whitespace": [
      1,
      {
        "skipTemplates": false,
        "skipRegExps": false,
        "skipHTMLTextContents": false,
        "skipComments": false,
        "skipStrings": true,
        "skipHTMLAttributeValues": false
      }
    ],
    "vue/no-lone-template": 1,
    "vue/no-loss-of-precision": 1,
    "vue/no-multiple-slot-args": 1,
    "vue/no-multiple-template-root": 1,
    "vue/no-parsing-error": 1,
    "vue/no-ref-object-reactivity-loss": 1,
    "vue/no-required-prop-with-default": 1,
    "vue/no-reserved-props": 1,
    "vue/no-restricted-class": 1,
    "vue/no-shared-component-data": 1,
    "vue/no-side-effects-in-computed-properties": 1,
    "vue/no-sparse-arrays": 1,
    "vue/no-template-key": 1,
    "vue/no-template-target-blank": 1,
    "vue/no-textarea-mustache": 1,
    "vue/no-this-in-before-route-enter": 1,
    "vue/no-use-computed-property-like-method": 1,
    "vue/no-useless-template-attributes": 1,
    "vue/no-v-for-template-key": 1,
    "vue/no-v-for-template-key-on-child": 1,
    "vue/no-v-model-argument": 1,
    "vue/no-v-text-v-html-on-component": 1,
    "vue/prefer-prop-type-boolean-first": 1,
    "vue/require-component-is": 1,
    "vue/require-default-export": 1,
    "vue/require-explicit-slots": 1,
    "vue/require-render-return": 1,
    "vue/require-slots-as-functions": 1,
    "vue/require-toggle-inside-transition": 1,
    "vue/require-v-for-key": 1,
    "vue/restricted-component-names": 1,
    "vue/return-in-computed-property": 1,
    "vue/return-in-emits-validator": 1,
    "vue-scoped-css/no-parsing-error": 1,
    "vuetify/no-deprecated-imports": 1,
    "vue/valid-attribute-name": 1,
    "vue/valid-define-emits": 1,
    "vue/valid-define-options": 1,
    "vue/valid-define-props": 1,
    "vue/valid-model-definition": 1,
    "vue/valid-next-tick": 1,
    "vue/valid-template-root": 1,
    "vue/valid-v-bind": 1,
    "vue/valid-v-bind-sync": 1,
    "vue/valid-v-cloak": 1,
    "vue/valid-v-else": 1,
    "vue/valid-v-else-if": 1,
    "vue/valid-v-for": 1,
    "vue/valid-v-html": 1,
    "vue/valid-v-if": 1,
    "vue/valid-v-is": 1,
    "vue/valid-v-memo": 1,
    "vue/valid-v-model": 1,
    "vue/valid-v-on": 1,
    "vue/valid-v-once": 1,
    "vue/valid-v-pre": 1,
    "vue/valid-v-show": 1,
    "vue/valid-v-slot": 1,
    "vue/valid-v-text": 1,
    "vue/v-if-else-key": 1,
    "wdio/await-expect": 1,
    "wdio/no-debug": 1,
    "wdio/no-pause": 1,
    "xss/no-location-href-assign": 1,
    "yml/no-irregular-whitespace": [
      1,
      {
        "skipComments": false,
        "skipQuotedScalars": true
      }
    ],
    "yml/no-tab-indent": 1,
    "yml/vue-custom-block_no-parsing-error": 1
  }
}
