name: Client Side Tools and Coverage

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Choose your Node.js version

      - name: Run Codacy CLI
        uses: codacy/codacy-cli-v2-action@main
        with:
          api_token: ${{ secrets.CODACY_API_TOKEN }}
          tool: eslint
          upload_report: true
          provider: gh
          owner: codacy-acme
          repository: sample-javascript-project

      - name: Install dependencies
        run: |
          npm install -g nyc  # Install Istanbul (nyc) for code coverage
          npm install  # Install project dependencies
          npm install --save-dev nyc
          npm install --save-dev chai
          npm install --save-dev blanket
          npm install --save-dev mocha
          npm install --save-dev mocha-lcov-reporter

      - name: Run tests and collect coverage
        run: |
          # Replace with the actual command to run your tests
          npm test
        continue-on-error: true

      - name: Upload coverage report to Codacy
        env:
            CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
            bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r $GITHUB_WORKSPACE/lcov.info
        continue-on-error: true
